import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';


const sidebars: SidebarsConfig = {
  nexusSidebar: [{type: 'autogenerated', dirName: 'nexus'}],
  vertexSidebar: [{type: 'autogenerated', dirName: 'vertex'}],
  beaconSidebar: [{type: 'autogenerated', dirName: 'beacon'}],
  aiPlatformSidebar: [{type: 'autogenerated', dirName: 'ai-platform'}],
  apiSidebar: [{type: 'autogenerated', dirName: 'api'}],
  mobileAppSidebar: [{type: 'autogenerated', dirName: 'mobile-app'}],
  dataAccessSidebar: [{type: 'autogenerated', dirName: 'data-access'}],
};

export default sidebars;
