import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';


const sidebars: SidebarsConfig = {
  analyticsSidebar: [{type: 'autogenerated', dirName: 'analytics'}],
  vertexSidebar: [{type: 'autogenerated', dirName: 'vertex'}],
  beaconSidebar: [{type: 'autogenerated', dirName: 'beacon'}],
  aiPlatformSidebar: [{type: 'autogenerated', dirName: 'ai-platform'}],
  apiSidebar: [{type: 'autogenerated', dirName: 'api'}],
  mobileAppSidebar: [{type: 'autogenerated', dirName: 'mobile-app'}],
  crossProductSidebar: [{type: 'autogenerated', dirName: 'cross-product'}],
};

export default sidebars;
