import { createSlice, PayloadAction } from '@reduxjs/toolkit';

interface Country {
  name: string;
  long_name: string;
  flag?: string;
  _id: string;
}

interface CountryState {
  selectedCountry: Country | null;
}

const initialState: CountryState = {
  selectedCountry: null,
};

export const countrySlice = createSlice({
  name: 'country',
  initialState,
  reducers: {
    // Action to set the selected country
    setSelectedCountry: (state, action: PayloadAction<Country>) => {
      state.selectedCountry = action.payload;
    },
    // Action to clear the selected country
    clearSelectedCountry: (state) => {
      state.selectedCountry = null;
    },
  },
});

// Export the actions generated by createSlice
export const { setSelectedCountry, clearSelectedCountry } =
  countrySlice.actions;

// Export the reducer to be included in the store
export default countrySlice.reducer;
