import { createSlice } from '@reduxjs/toolkit';

// Define the initial state for the modal
interface ModalState {
  isOpen: boolean;
}

const initialState: ModalState = {
  isOpen: false,
};

// Create a slice for the modal
const modalSlice = createSlice({
  name: 'modal',
  initialState,
  reducers: {
    openModal: (state: any) => {
      state.isOpen = true;
    },
    closeModal: (state: any) => {
      state.isOpen = false;
    },
    toggleModal: (state: any) => {
      state.isOpen = !state.isOpen;
    },
  },
});

// Export the actions generated by createSlice
export const { openModal, closeModal, toggleModal } = modalSlice.actions;

// Export the reducer to be used in the store
export default modalSlice.reducer;
