export const LOAD_ALL_AIRQLOUDS_SUCCESS = "LOAD_ALL_AIRQLOUDS_SUCCESS";
export const LOAD_ALL_AIRQLOUDS_FAILURE = "LOAD_ALL_AIRQLOUDS_FAILURE";

export const SET_CURRENT_AIRQLOUD_SUCCESS = "SET_CURRENT_AIRQLOUD_SUCCESS";
export const SET_CURRENT_AIRQLOUD_FAILURE = "SET_CURRENT_AIRQLOUD_FAILURE";
