export const LOAD_ALL_AIRQLOUDS_SUCCESS = 'LOAD_ALL_AIRQLOUDS_SUCCESS';
export const LOAD_ALL_AIRQLOUDS_FAILURE = 'LOAD_ALL_AIRQLOUDS_FAILURE';

export const SET_CURRENT_AIRQLOUD_SUCCESS = 'SET_CURRENT_AIRQLOUD_SUCCESS';
export const SET_CURRENT_AIRQLOUD_FAILURE = 'SET_CURRENT_AIRQLOUD_FAILURE';

export const LOAD_DASHBOARD_AIRQLOUDS_SUCCESS = 'LOAD_DASHBOARD_AIRQLOUDS_SUCCESS';
export const LOAD_DASHBOARD_AIRQLOUDS_FAILURE = 'LOAD_DASHBOARD_AIRQLOUDS_FAILURE';

export const LOAD_SELECTED_AIRQLOUD_SUCCESS = 'LOAD_SELECTED_AIRQLOUD_SUCCESS';
export const LOAD_SELECTED_AIRQLOUD_FAILURE = 'LOAD_SELECTED_AIRQLOUD_FAILURE';

export const REMOVE_SELECTED_AIRQLOUD_SUCCESS = 'REMOVE_SELECTED_AIRQLOUD_SUCCESS';
