// contains all the action creator functions.
export const LOAD_ALL_DEVICES_SUCCESS = "LOAD_ALL_DEVICES_SUCCESS";
export const LOAD_ALL_DEVICES_FAILURE = "LOAD_ALL_DEVICES_FAILURE";

export const LOAD_MAINTENANCE_LOGS_SUCCESS = "LOAD_MAINTENANCE_LOGS_SUCCESS";
export const LOAD_MAINTENANCE_LOGS_FAILURE = "LOAD_MAINTENANCE_LOGS_FAILURE";
