apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.configmap }}
  namespace: {{ .Values.app.namespace }}
  labels:
    {{- include "internal-docs.labels" . | nindent 4 }}
data:
  # BookStack Specific
  APP_NAME: {{ .Values.env.APP_NAME | quote }}
  APP_KEY: {{ .Values.env.APP_KEY | quote }}
  APP_PUBLIC: {{ .Values.env.APP_PUBLIC | quote }}
  
  # Shared Database Configuration (Used by BookStack container)
  DB_USER: {{ .Values.env.DB_USER | quote }}
  DB_PASS: {{ .Values.env.DB_PASSWORD | quote }}
  DB_DATABASE: {{ .Values.env.DB_DATABASE | quote }}
  
  # MariaDB Specific (Used by MariaDB container)
  MYSQL_USER: {{ .Values.env.DB_USER | quote }}
  MYSQL_PASSWORD: {{ .Values.env.DB_PASSWORD | quote }}
  MYSQL_DATABASE: {{ .Values.env.DB_DATABASE | quote }}
  MYSQL_ROOT_PASSWORD: {{ .Values.env.MYSQL_ROOT_PASSWORD | quote }}
