apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.app.name }}-pvc
  namespace: {{ .Values.app.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.dbApp.name }}-pvc
  namespace: {{ .Values.app.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.dbPersistence.storageClass }}
  storageClassName: {{ .Values.dbPersistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.dbPersistence.size }}
