apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.dbApp.name }}
  namespace: {{ .Values.app.namespace }}
  labels:
    {{- include "internal-docs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.dbService.type }}
  ports:
    - port: {{ .Values.dbService.port }}
      targetPort: {{ .Values.dbService.targetPort }}
      protocol: TCP
      name: mysql
  selector:
    app: {{ .Values.dbApp.label }}
