import type { Cohort } from "@/app/types/cohorts";
import type { Device, PaginationMeta } from "@/app/types/devices";
import type { Site } from "@/app/types/sites";
import type { UserDetails } from "@/app/types/users";
import type { Network } from "@/core/apis/networks";
import type { DeviceActivity } from "@/core/apis/devices";
import { PERMISSIONS } from "@/core/permissions/constants";

const now = "2026-05-30T09:00:00.000Z";
const yesterday = "2026-05-29T09:00:00.000Z";

export const mockPaginationMeta: PaginationMeta = {
  total: 0,
  totalResults: 0,
  limit: 100,
  skip: 0,
  page: 1,
  totalPages: 1,
  detailLevel: "summary",
  usedCache: false,
};

// Grant the demo admin every permission except system-level ones so the
// whole app is explorable in mock mode. Derived from the RBAC constants
// so the permission strings cannot drift out of sync.
const demoPermissions = Object.entries(PERMISSIONS)
  .filter(([group]) => group !== "SYSTEM")
  .flatMap(([, group]) => Object.values(group));

export const mockRole = {
  _id: "role-demo-admin",
  role_name: "DEMO_ADMIN",
  role_permissions: demoPermissions.map((permission) => ({
    _id: `perm-${permission.toLowerCase().replace(/_/g, "-")}`,
    permission,
  })),
};

export const mockNetworks: Network[] = [
  {
    _id: "network-demo",
    net_status: "active",
    net_acronym: "DEMO",
    net_name: "demo-network",
    net_email: "support@example.org",
    net_website: "https://example.org",
    net_phoneNumber: "+256700000000",
    net_category: "research",
    net_description: "Demo sensor network for local Vertex evaluation.",
    net_profile_picture: "",
    createdAt: "2026-01-01T00:00:00.000Z",
    net_manager: {
      _id: "user-demo-admin",
      email: "admin@example.org",
      firstName: "Demo",
      lastName: "Admin",
      group_roles: [],
      isActive: true,
      lastLogin: now,
      verified: true,
      description: "Demo administrator",
      jobTitle: "Platform Manager",
      website: "https://example.org",
      loginCount: 1,
      analyticsVersion: 4,
      preferredTokenStrategy: "jwt",
    },
    net_users: [],
    net_permissions: [],
    net_roles: [],
    net_departments: [],
  },
];

export const mockUser: UserDetails = {
  _id: "user-demo-admin",
  firstName: "Demo",
  lastName: "Admin",
  lastLogin: now,
  isActive: true,
  loginCount: 1,
  userName: "demo.admin",
  email: "admin@example.org",
  verified: true,
  analyticsVersion: 4,
  country: "Uganda",
  privilege: "admin",
  website: "https://example.org",
  category: "research",
  organization: "Vertex Demo",
  long_organization: "Vertex Demo",
  rateLimit: null,
  jobTitle: "Platform Manager",
  description: "Seeded mock user for local Vertex evaluation.",
  timezone: "Africa/Kampala",
  profilePicture: null,
  phoneNumber: null,
  updatedAt: now,
  networks: [
    {
      _id: "network-demo",
      net_name: "demo-network",
      role: mockRole,
      userType: "admin",
      createdAt: "2026-01-01T00:00:00.000Z",
      status: "active",
    },
  ],
  clients: [],
  groups: [
    {
      _id: "group-demo",
      grp_title: "system",
      createdAt: "2026-01-01T00:00:00.000Z",
      status: "active",
      role: mockRole,
      userType: "admin",
    },
  ],
  permissions: mockRole.role_permissions,
  createdAt: "2026-01-01T00:00:00.000Z",
  my_networks: ["network-demo"],
  my_groups: ["group-demo"],
  group_ids: ["group-demo"],
  cohort_ids: ["cohort-central", "cohort-schools"],
};

export const mockSites: Site[] = [
  {
    _id: "site-central",
    name: "central-library",
    formatted_name: "Central Library",
    location_name: "Central Library, Kampala",
    search_name: "Central Library Kampala",
    city: "Kampala",
    district: "Kampala",
    region: "Central",
    country: "Uganda",
    latitude: 0.3136,
    longitude: 32.5811,
    network: "demo-network",
    groups: ["system"],
    site_tags: ["urban", "roadside"],
    isOnline: true,
    rawOnlineStatus: true,
    createdAt: "2026-01-10T00:00:00.000Z",
    lastActive: now,
    description: "Urban monitoring site near the central library.",
    devices: [],
  },
  {
    _id: "site-school",
    name: "green-hill-school",
    formatted_name: "Green Hill School",
    location_name: "Green Hill School, Kampala",
    search_name: "Green Hill School Kampala",
    city: "Kampala",
    district: "Kampala",
    region: "Central",
    country: "Uganda",
    latitude: 0.3368,
    longitude: 32.6015,
    network: "demo-network",
    groups: ["system"],
    site_tags: ["school", "community"],
    isOnline: false,
    rawOnlineStatus: false,
    createdAt: "2026-01-12T00:00:00.000Z",
    lastActive: yesterday,
    description: "Community monitoring site at a school campus.",
    devices: [],
  },
  {
    _id: "site-market",
    name: "nakawa-market",
    formatted_name: "Nakawa Market",
    location_name: "Nakawa Market, Kampala",
    search_name: "Nakawa Market Kampala",
    city: "Kampala",
    district: "Kampala",
    region: "Central",
    country: "Uganda",
    latitude: 0.3322,
    longitude: 32.6163,
    network: "demo-network",
    groups: ["system"],
    site_tags: ["market", "traffic"],
    isOnline: true,
    rawOnlineStatus: true,
    createdAt: "2026-01-15T00:00:00.000Z",
    lastActive: now,
    description: "Busy market monitoring site.",
    devices: [],
  },
];

export const mockDevices: Device[] = [
  {
    _id: "device-kla-001",
    id: "device-kla-001",
    name: "demo_g5241",
    long_name: "Demo Monitor G5241",
    alias: "Central Library Monitor",
    network: "demo-network",
    groups: ["system"],
    serial_number: "DM-G5241",
    authRequired: true,
    latitude: 0.3136,
    longitude: 32.5811,
    createdAt: "2026-01-20T00:00:00.000Z",
    visibility: true,
    description: "Demo deployed monitor with recent readings.",
    isPrimaryInLocation: true,
    nextMaintenance: "2026-07-01T00:00:00.000Z",
    deployment_date: "2026-02-01T00:00:00.000Z",
    mountType: "pole",
    isActive: true,
    isOnline: true,
    site_id: "site-central",
    height: 3,
    device_codes: ["DM-G5241"],
    category: "lowcost",
    cohorts: ["cohort-central"],
    device_number: 5241,
    generation_version: 2,
    site_name: "Central Library",
    status: "deployed",
    maintenance_status: "good",
    powerType: "solar",
    claim_status: "claimed",
    claimed_at: "2026-01-21T00:00:00.000Z",
    site: { _id: "site-central", name: "Central Library" },
    lastActive: now,
    rawOnlineStatus: true,
    tags: ["urban", "roadside"],
  },
  {
    _id: "device-kla-002",
    id: "device-kla-002",
    name: "demo_g5242",
    long_name: "Demo Monitor G5242",
    alias: "School Monitor",
    network: "demo-network",
    groups: ["system"],
    serial_number: "DM-G5242",
    authRequired: true,
    latitude: 0.3368,
    longitude: 32.6015,
    createdAt: "2026-01-22T00:00:00.000Z",
    visibility: true,
    description: "Demo monitor that is currently offline.",
    isPrimaryInLocation: true,
    nextMaintenance: "2026-06-10T00:00:00.000Z",
    deployment_date: "2026-02-05T00:00:00.000Z",
    mountType: "wall",
    isActive: true,
    isOnline: false,
    site_id: "site-school",
    height: 2.5,
    device_codes: ["DM-G5242"],
    category: "lowcost",
    cohorts: ["cohort-schools"],
    device_number: 5242,
    generation_version: 2,
    site_name: "Green Hill School",
    status: "offline",
    maintenance_status: "due",
    powerType: "mains",
    claim_status: "claimed",
    claimed_at: "2026-01-23T00:00:00.000Z",
    site: { _id: "site-school", name: "Green Hill School" },
    lastActive: yesterday,
    rawOnlineStatus: false,
    tags: ["school"],
  },
  {
    _id: "device-kla-003",
    id: "device-kla-003",
    name: "demo_g5243",
    long_name: "Demo Monitor G5243",
    alias: "Market Monitor",
    network: "demo-network",
    groups: ["system"],
    serial_number: "DM-G5243",
    authRequired: true,
    latitude: 0.3322,
    longitude: 32.6163,
    createdAt: "2026-01-25T00:00:00.000Z",
    visibility: false,
    description: "Demo monitor in private evaluation mode.",
    isPrimaryInLocation: true,
    nextMaintenance: "2026-05-20T00:00:00.000Z",
    deployment_date: "2026-02-08T00:00:00.000Z",
    mountType: "pole",
    isActive: true,
    isOnline: true,
    site_id: "site-market",
    height: 3.5,
    device_codes: ["DM-G5243"],
    category: "lowcost",
    cohorts: ["cohort-central"],
    device_number: 5243,
    generation_version: 2,
    site_name: "Nakawa Market",
    status: "online",
    maintenance_status: "overdue",
    powerType: "solar",
    claim_status: "claimed",
    claimed_at: "2026-01-26T00:00:00.000Z",
    site: { _id: "site-market", name: "Nakawa Market" },
    lastActive: now,
    rawOnlineStatus: true,
    tags: ["market", "traffic"],
  },
  {
    _id: "device-kla-004",
    id: "device-kla-004",
    name: "demo_g5244",
    long_name: "Demo Monitor G5244",
    network: "demo-network",
    groups: ["system"],
    serial_number: "DM-G5244",
    authRequired: true,
    createdAt: "2026-01-28T00:00:00.000Z",
    visibility: false,
    description: "Claimed but not yet deployed demo monitor.",
    isActive: true,
    isOnline: false,
    device_codes: ["DM-G5244"],
    category: "lowcost",
    cohorts: [],
    device_number: 5244,
    generation_version: 2,
    status: "not deployed",
    maintenance_status: -1,
    claim_status: "claimed",
    claimed_at: "2026-01-29T00:00:00.000Z",
    lastActive: yesterday,
    rawOnlineStatus: false,
    tags: ["inventory"],
  },
];

export const mockCohorts: Cohort[] = [
  {
    _id: "cohort-central",
    visibility: true,
    cohort_tags: ["urban", "traffic"],
    cohort_codes: ["central"],
    name: "Central City Devices",
    network: "demo-network",
    groups: ["system"],
    numberOfDevices: 2,
    devices: mockDevices
      .filter((device) => device.cohorts.includes("cohort-central"))
      .map((device) => ({
        _id: device._id || device.name,
        name: device.name,
        network: device.network,
        groups: device.groups || [],
        authRequired: !!device.authRequired,
        serial_number: device.serial_number,
        api_code: device.api_code || "",
        long_name: device.long_name || device.name,
      })),
    createdAt: "2026-02-01T00:00:00.000Z",
  },
  {
    _id: "cohort-schools",
    visibility: false,
    cohort_tags: ["school", "community"],
    cohort_codes: ["schools"],
    name: "School Monitoring Devices",
    network: "demo-network",
    groups: ["system"],
    numberOfDevices: 1,
    devices: mockDevices
      .filter((device) => device.cohorts.includes("cohort-schools"))
      .map((device) => ({
        _id: device._id || device.name,
        name: device.name,
        network: device.network,
        groups: device.groups || [],
        authRequired: !!device.authRequired,
        serial_number: device.serial_number,
        api_code: device.api_code || "",
        long_name: device.long_name || device.name,
      })),
    createdAt: "2026-02-02T00:00:00.000Z",
  },
];

export const mockDeviceActivities: DeviceActivity[] = [
  {
    _id: "activity-001",
    device: "demo_g5241",
    date: now,
    description: "Device transmitted latest measurements.",
    activityType: "online",
    activity_by: {
      user_id: "user-demo-admin",
      name: "Demo Admin",
      email: "admin@example.org",
    },
    site_id: "site-central",
    network: "demo-network",
    createdAt: now,
  },
  {
    _id: "activity-002",
    device: "demo_g5242",
    date: yesterday,
    description: "Device stopped transmitting.",
    activityType: "offline",
    activity_by: {
      user_id: "user-demo-admin",
      name: "Demo Admin",
      email: "admin@example.org",
    },
    site_id: "site-school",
    network: "demo-network",
    createdAt: yesterday,
  },
  {
    _id: "activity-003",
    device: "demo_g5243",
    date: now,
    description: "Maintenance is overdue.",
    activityType: "maintenance",
    activity_by: {
      user_id: "user-demo-admin",
      name: "Demo Admin",
      email: "admin@example.org",
    },
    site_id: "site-market",
    network: "demo-network",
    nextMaintenance: "2026-05-20T00:00:00.000Z",
    createdAt: now,
  },
];

