export const LOAD_AIRQLOUDS_SUMMARY_SUCCESS = 'LOAD_AIRQLOUDS_SUMMARY_SUCCESS';
export const LOAD_AIRQLOUDS_SUMMARY_FAILURE = 'LOAD_AIRQLOUDS_SUMMARY_FAILURE';

export const SET_CURRENT_AIRQLOUD_SUCCESS = 'SET_CURRENT_AIRQLOUD_SUCCESS';
export const SET_CURRENT_AIRQLOUD_FAILURE = 'SET_CURRENT_AIRQLOUD_FAILURE';
