export const LOAD_ALL_USER_ROLES_SUCCESS = 'LOAD_ALL_USER_ROLES_SUCCESS';
export const LOAD_ALL_USER_ROLES_FAILURE = 'LOAD_ALL_USER_ROLES_FAILURE';

export const LOAD_CURRENT_USER_ROLE_SUCCESS = 'LOAD_CURRENT_USER_ROLE_SUCCESS';
export const LOAD_CURRENT_USER_ROLE_FAILURE = 'LOAD_CURRENT_USER_ROLE_FAILURE';
