replicaCount: 1
image:
  repository: airqoacr.azurecr.io/airqo-nexus
  tag: prod-ede8906d-1784755139
  pullPolicy: IfNotPresent
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
service:
  type: NodePort
  protocol: TCP
  nodePort: 30117
  targetPort: 3000
  port: 3000
ingress:
  enabled: false
resources:
  requests:
    cpu: 100m
    memory: 300Mi
  limits:
    cpu: 500m
    memory: 700Mi
autoscaling:
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
        - type: Pods
          value: 2
          periodSeconds: 60
app:
  name: airqo-nexus
  label: airqo-nexus
  namespace: production
  secret: prod-env-nexus
