// contains all the action creator functions.
export const REFRESH_FILTER_LOCATION_DATA_SUCCESS =
  "REFRESH_FILTER_LOCATION_DATA_SUCCESS";
export const REFRESH_FILTER_LOCATION_DATA_ERROR =
  "REFRESH_FILTER_LOCATION_DATA_FAILURE";
