// contains all the action creator functions.
export const REFRESH_FILTER_LOCATION_DATA_SUCCESS =
  "REFRESH_FILTER_LOCATION_DATA_SUCCESS";
export const REFRESH_FILTER_LOCATION_DATA_ERROR =
  "REFRESH_FILTER_LOCATION_DATA_FAILURE";

export const LOAD_USER_DEFAULT_GRAPHS_SUCCESS =
  "LOAD_USER_DEFAULT_GRAPHS_SUCCESS";
export const LOAD_USER_DEFAULT_GRAPHS_ERROR = "LOAD_USER_DEFAULT_GRAPHS_ERROR";

export const SET_USER_DEFAULTS_GRAPHS_SUCCESS =
  "SET_USER_DEFAULTS_GRAPHS_SUCCESS";
export const SET_USER_DEFAULTS_GRAPHS_ERROR = "SET_USER_DEFAULTS_GRAPHS_ERROR";
