export const LOAD_CAREERS_SUCCESS = 'LOAD_CAREERS_SUCCESS';
export const LOAD_CAREERS_FAILURE = 'LOAD_CAREERS_FAILURE';

export const UPDATE_CAREERS_LOADER_SUCCESS = 'UPDATE_CAREERS_LOADER_SUCCESS';
export const UPDATE_CAREERS_LOADER_FAILURE = 'UPDATE_CAREERS_LOADER_FAILURE';

