export default [{
        location_ref: "rwrwr",
        device_ref: "wefww",
        channel_id: "wefww",
        host_name: "Ekaterina scvsfwerf",
        address: {
            country: "Uganda",
            region: "qrwerwr3",
            district: "qrqretqetq",
            subcounty: "qrqrqe3242",
            parish: "tata",
        },
        latitude: "34354613",
        longitude: "41243541",
        createdAt: 1555016400000,
    },
    {
        location_ref: "yutut",
        device_ref: "egee",
        channel_id: "dgergerte",
        host_name: "wfwerw wfwerw",
        address: {
            country: "Uganda",
            region: "qrwerwr3",
            district: "qrqretqetq",
            subcounty: "qrqrqe3242",
            parish: "tata",
        },
        latitude: "34365613",
        longitude: "41464341",
        createdAt: 1555016400000,
    },
    {
        location_ref: "dergeg",
        device_ref: "eeete",
        channel_id: "egegete",
        host_name: "wfwfwfw wfwfwefw",
        address: {
            country: "Uganda",
            region: "qrwerwr3",
            district: "qrqretqetq",
            subcounty: "qrqrqe3242",
            parish: "tata",
        },
        latitude: "34454613",
        longitude: "44646341",
        createdAt: 1554930000000,
    },
    {
        location_ref: "wfwefwef",
        device_ref: "wfwefwefwe",
        channel_id: "wefwefwef",
        host_name: "afwefwe kffasfke",
        address: {
            country: "Uganda",
            region: "qrwerwr3",
            district: "qrqretqetq",
            subcounty: "qrqrqe3242",
            parish: "tata",
        },
        latitude: "34353513",
        longitude: "415757841",
        createdAt: 1554757200000,
    },
    {
        location_ref: "wfwefwef",
        device_ref: "wfwefwefwe",
        channel_id: "wefwefwef",
        host_name: "afwefwe kffasfke",
        address: {
            country: "Uganda",
            region: "qrwerwr3",
            district: "qrqretqetq",
            subcounty: "qrqrqe3242",
            parish: "tata",
        },
        latitude: "345867313",
        longitude: "4135353341",
        createdAt: 1554670800000,
    },
    {
        location_ref: "wfwefwef",
        device_ref: "wfwefwefwe",
        channel_id: "wefwefwef",
        host_name: "afwefwe kffasfke",
        address: {
            country: "Uganda",
            region: "qrwerwr3",
            district: "qrqretqetq",
            subcounty: "qrqrqe3242",
            parish: "tata",
        },
        latitude: "342342313",
        longitude: "4134343341",
        createdAt: 1554325200000,
    },
];