export const LEGACY_PLATFORM_ENV = process.env.NEXT_PUBLIC_ORIGINAL_PLATFORM;
export const NEXT_PUBLIC_AUTHORISATION = process.env.NEXT_PUBLIC_AUTHORISATION;
export const NEXT_PUBLIC_BASE_DEVICE_MONITORING_URL =
  process.env.NEXT_PUBLIC_BASE_DEVICE_MONITORING_URL;
export const NEXT_PUBLIC_API_TOKEN = process.env.NEXT_PUBLIC_API_TOKEN;
export const NEXT_PUBLIC_API_BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL;
