require:
  - ts-node/register
timeout: 30000
recursive: true
spec: "tests/**/*.test.ts"
reporter: mochawesome
reporter-options:
  - reportDir=reports
  - reportTitle=AirQo E2E Tests
  - json=false
  - cdn=true
