replicaCount: 2
image:
  repository: eu.gcr.io/airqo-250220/airqo-stage-reports
  tag: stage-07e1532b-1740386563
  pullPolicy: Always
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
service:
  type: NodePort
  nodePort: 31112
  targetPort: 3000
  port: 3000
ingress:
  enabled: false
torelations: {}
resources:
  requests:
    cpu: 10m
    memory: 150Mi
  limits:
    cpu: 50m
    memory: 200Mi
autoscaling:
  minReplicas: 1
  maxReplicas: 3
  targetMemoryUtilizationPercentage: 80
nodeSelector:
  role: control-plane
affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - preference:
          matchExpressions:
            - key: role
              operator: In
              values:
                - control-plane
        weight: 1
app:
  name: airqo-stage-reports
  label: airqo-reports
  namespace: staging
  configmap: env-reports-staging
