# Generated by Django 4.2.5 on 2024-02-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_publication_resource_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='authors_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='authors_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='link_title_en',
            field=models.CharField(blank=True, default='Read More', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='link_title_fr',
            field=models.CharField(blank=True, default='Read More', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='title_fr',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
