# Generated by Django 4.1.7 on 2023-07-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_alter_publication_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='resource_file',
            field=models.FileField(blank=True, null=True, upload_to='publications/'),
        ),
    ]
