/**setting the current user */
export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER_REQUEST = "SET_CURRENT_USER_REQUEST";
export const SET_CURRENT_USER_SUCCESS = "SET_CURRENT_USER_SUCCESS";
export const SET_CURRENT_USER_FAILED = "SET_CURRENT_USER_FAILED";

/**confirming user's email address */
export const CONFIRM_EMAIL_REQUEST = "CONFIRM_EMAIL_REQUEST";
export const CONFIRM_EMAIL_SUCCESS = "CONFIRM_EMAIL_SUCCESS";
export const CONFIRM_EMAIL_FAILED = "CONFIRM_EMAIL_FAILED";

/** adding a new user*/
export const ADD_USER_REQUEST = "ADD_USER_REQUEST";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAILED = "ADD_USER_FAILED";

/*** adding a new candidate */
export const ADD_CANDIDATE_REQUEST = "ADD_CANDIDATE_REQUEST";
export const ADD_CANDIDATE_SUCCESS = "ADD_CANDIDATE_SUCCESS";
export const ADD_CANDIDATE_FAILED = "ADD_CANDIDATE_FAILED";

/** forgot password  */
export const FORGOT_PWD_REQUEST = "FORGOT_PWD_REQUEST";
export const FORGOT_PWD_SUCCESS = "FORGOT_PWD_SUCCESS";
export const FORGOT_PWD_FAILED = "FORGOT_PWD_FAILED";

/**reset password */
export const RESET_PWD_REQUEST = "RESET_PWD_REQUEST";
export const RESET_PWD_SUCCESS = "RESET_PWD_SUCCESS";
export const RESET_PWD_FAILED = "RESET_PWD_FAILED";

/**update password */
export const UPDATE_PWD_REQUEST = "UPDATE_PWD_REQUEST ";
export const UPDATE_PWD_SUCCESS = "UPDATE_PWD_SUCCESS";
export const UPDATE_PWD_FAILED = "UPDATE_PWD_FAILED";

/** load users */
export const LOAD_USERS_REQUEST = "LOAD_USERS_REQUEST";
export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS";
export const LOAD_USERS_FAILED = "LOAD_USERS_FAILED";

/** update user  */
export const UPDATE_USER_REQUEST = "UPDATE_USERS_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USERS_SUCCESS";
export const UPDATE_USER_FAILED = "UPDATE_USER_FAILED";

/** delete user */
export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILED = "DELETE_USER_FAILED";

/** load graph defaults */
export const LOAD_DEFAULTS_REQUEST = "LOAD_DEFAULTS_REQUEST";
export const LOAD_DEFAULTS_SUCCESS = "LOAD_DEFAULTS_SUCCESS";
export const LOAD_DEFAULTS_FAILED = "LOAD_DEFAULTS_FAILED";

/*** set defaults */
export const SET_DEFAULTS_REQUEST = "SET_DEFAULTS_REQUEST";
export const SET_DEFAULTS_SUCCESS = "SET_DEFAULTS_SUCCESS";
export const SET_DEFAULTS_FAILED = "SET_DEFAULTS_FAILED";
