apiVersion: v2
appVersion: "1.0.0"
description: AirQo Internal Docs (The Mariana) Helm Chart
name: airqo-internal-docs
home: https://airqo.net
version: 0.1.0
maintainers:
  - name: AirQo
    email: support@airqo.net
    url: https://airqo.net
