# Generated by Django 4.0.5 on 2022-07-13 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_bulletdescription_alter_career_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bulletpoint',
            old_name='Bullet',
            new_name='bullet',
        ),
        migrations.RenameField(
            model_name='bulletpoint',
            old_name='description',
            new_name='point',
        ),
    ]
