# Generated by Django 4.0.5 on 2022-07-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0004_career_unique_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bulletdescription',
            options={},
        ),
        migrations.AlterModelOptions(
            name='bulletpoint',
            options={},
        ),
        migrations.AlterModelOptions(
            name='career',
            options={},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={},
        ),
        migrations.AlterModelOptions(
            name='jobdescription',
            options={},
        ),
        migrations.AddField(
            model_name='bulletdescription',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bulletpoint',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='career',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='department',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
