# Generated by Django 3.2.14 on 2022-07-18 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0005_alter_bulletdescription_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bulletdescription',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='bulletpoint',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='jobdescription',
            options={'ordering': ['order']},
        ),
    ]
