# Generated by Django 4.2.5 on 2024-02-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0006_auto_20220718_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletdescription',
            name='name_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bulletdescription',
            name='name_fr',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bulletpoint',
            name='point_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bulletpoint',
            name='point_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='career',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='career',
            name='title_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='name_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='name_fr',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='description_fr',
            field=models.TextField(null=True),
        ),
    ]
