// Import global styles
import "./globals.scss";

// Import required modules
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import StoreProvider from "./StoreProvider";
import { Toaster } from "@/components/ui/sonner";
import SessionAndThemeProvider from "@/app/SessionAndThemeProvider";

// Set up the Inter font
const inter = Inter({ subsets: ["latin"] });

// Define the metadata for the app
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Define the RootLayout component
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <SessionAndThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <StoreProvider>{children}</StoreProvider>
        </SessionAndThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}
