export const ROUTE_LINKS = {
  HOME: '/home',
  ADMIN_NETWORKS: '/admin/networks',
  ADMIN_NETWORK_REQUESTS: '/admin/networks/requests',
  COHORTS: '/admin/cohorts',
  SITES: '/admin/sites',
  GRIDS: '/admin/grids',
  ADMIN_SHIPPING: '/admin/shipping',
  MY_DEVICES: '/devices/my-devices',
  ORG_OVERVIEW: '/home',
  ORG_ASSETS: '/devices/overview',
  ORG_REGISTER_DEVICE: '/devices/claim',
  DEVICE_COHORTS: '/cohorts',
  ORG_SITES: '/sites/overview',
  SITE_DETAILS: '/sites',
};
