# Generated by Django 4.2.2 on 2023-07-10 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_phone_profile_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
