export const GET_INVOLVED_REGISTRATION_SUCCESS = 'GET_INVOLVED_REGISTRATION_SUCCESS';
export const GET_INVOLVED_REGISTRATION_FAILURE = 'GET_INVOLVED_REGISTRATION_FAILURE';

export const SHOW_GET_INVOLVED_MODAL_SUCCESS = 'SHOW_GET_INVOLVED_MODAL_SUCCESS';
export const SHOW_GET_INVOLVED_MODAL_FAILURE = 'SHOW_GET_INVOLVED_MODAL_FAILURE';

export const UPDATE_GET_INVOLVED_DATA_SUCCESS = 'UPDATE_GET_INVOLVED_DATA_SUCCESS';
export const UPDATE_GET_INVOLVED_DATA_FAILURE = 'UPDATE_GET_INVOLVED_DATA_FAILURE';
