export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const CONFIRM_EMAIL_REQUEST = "CONFIRM_EMAIL_REQUEST";
export const WELCOME_EMAIL_REQUEST = "WELCOME_EMAIL_REQUEST";
export const RECOVERY_EMAIL_REQUEST = "RECOVERY_EMAIL_REQUEST";

export const RESET_PWD_REQUEST = "RESET_PWD_REQUEST";
export const RESET_PWD_SUCCESS = "RESET_PWD_SUCCESS";
export const UPDATE_PWD_REQUEST = "UPDATE_PWD_REQUEST ";

export const LOAD_USERS_REQUEST = "LOAD_USERS_REQUEST";
export const ACTIVATE_USER_REQUEST = "ACTIVATE_USER_REQUEST";
export const DEACTIVATE_USER_REQUEST = "DEACTIVATE_USER_REQUEST";
