# Generated by Django 4.1.1 on 2022-09-26 07:20

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='partner_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='PartnerImage'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='type',
            field=models.CharField(blank=True, choices=[('partnership', 'Partnership'), ('collaboration', 'Collaboration'), ('policy', 'Policy')], default='partnership', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='partnerdescription',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
