# Generated by Django 4.1.7 on 2023-09-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_alter_partner_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='website_category',
            field=models.CharField(blank=True, choices=[('airqo', 'AirQo'), ('cleanair', 'CleanAir')], default='airqo', max_length=40, null=True),
        ),
    ]
