/**
 * Types for Grid data
 */
export interface GridsData {
  success: boolean
  message: string
  grids: Grid[]
}

export interface Grid {
  _id: string
  grid_tags: string[]
  visibility: boolean
  grid_codes: string[]
  name: string
  admin_level: string
  shape: Shape
  network: string
  centers: Center[]
  long_name: string
  createdAt: string
  sites: Site[]
  numberOfSites: number
}

export interface Center {
  longitude: number
  latitude: number
}

export interface Shape {
  type: string
  coordinates: Array<Array<number[]>>
}

export interface Site {
  _id: string
  formatted_name: string
  parish: string
  sub_county: string
  city: string
  region: string
  country: string
  latitude: number
  longitude: number
  name: string
  approximate_latitude: number
  approximate_longitude: number
  bearing_in_radians: number
  approximate_distance_in_km: number
  generated_name: string
  location_name: string
  search_name: string
  data_provider: string
  images?: string[]
  land_use?: string
}

/**
 * Types for Report data
 */
// Generated by https://quicktype.io

export interface ReportData {
  airquality: Airquality
}

export interface Airquality {
  annual_pm: AnnualPm[]
  daily_mean_pm: AnnualPm[]
  datetime_mean_pm: DatetimeMeanPm[]
  diurnal: DatetimeMeanPm[]
  grid_id: string
  mean_pm_by_city: MeanPmByCity[]
  mean_pm_by_country: AnnualPm[]
  mean_pm_by_day_hour: DatetimeMeanPm[]
  mean_pm_by_day_of_week: AnnualPm[]
  mean_pm_by_region: AnnualPm[]
  monthly_pm: AnnualPm[]
  period: Period
  pm_by_month_name: AnnualPm[]
  pm_by_month_year: AnnualPm[]
  site_annual_mean_pm: SiteMeanPm[]
  site_mean_pm: SiteMeanPm[]
  site_monthly_mean_pm: SiteMeanPm[]
  sites: Sites
  status: string
}

export interface AnnualPm {
  pm10_calibrated_value: number
  pm10_raw_value: number
  pm2_5_calibrated_value: number
  pm2_5_raw_value: number
  year?: number
  date?: string
  country?: string
  day?: Day
  region?: string
  month?: number
  month_name?: string
}

export enum Day {
  Friday = 'Friday',
  Monday = 'Monday',
  Saturday = 'Saturday',
  Sunday = 'Sunday',
  Thursday = 'Thursday',
  Tuesday = 'Tuesday',
  Wednesday = 'Wednesday',
}

export interface DatetimeMeanPm {
  pm10_calibrated_value: number | string
  pm10_raw_value: number
  pm2_5_calibrated_value: number | string
  pm2_5_raw_value: number
  timestamp?: string
  hour?: number
  day?: Day
}

export interface MeanPmByCity {
  city: string
  month: number
  pm10_calibrated_value: number
  pm10_raw_value: number
  pm2_5_calibrated_value: number
  pm2_5_raw_value: number
  year: number
}

export interface Period {
  endTime: string
  startTime: string
}

export interface SiteMeanPm {
  pm10_calibrated_value: number
  pm10_raw_value: number
  pm2_5_calibrated_value: number
  pm2_5_raw_value: number
  site_latitude: number
  site_longitude: number
  site_name: string
  year?: number
  month?: number
}

export interface Sites {
  'grid name': string[]
  number_of_sites: number
  site_ids: string[]
}
