export const AQI_FOR_CITIES = [
  'Tokyo',
  'Delhi',
  'Shanghai',
  'Sao Paulo',
  'Mumbai',
  'Mexico City',
  'Beijing',
  'Osaka',
  'Cairo',
  'New York',
  'Dhaka',
  'Karachi',
  'Buenos Aires',
  'Istanbul',
  'Kolkata',
  'Manila',
  'Lagos',
  'Rio de Janeiro',
  'Kinshasa',
  'Guangzhou',
  'Los Angeles',
  'Moscow',
  'Shenzhen',
  'Lahore',
  'Bangalore',
  'Paris',
  'Bogota',
  'Jakarta',
  'Chennai',
  'Lima',
  'Bangkok',
  'Seoul',
  'Nagoya',
  'Hyderabad',
  'London',
  'Tehran',
  'Chicago',
  'Chengdu',
  'Nanjing',
  'Wuhan',
  'Ho Chi Minh City',
  'Luanda',
  'Ahmedabad',
  'Kuala Lumpur',
  'Hangzhou',
  'Hong Kong',
  'Dongguan',
  'Foshan',
  'Riyadh',
  'Baghdad',
  'Santiago',
  'Singapore',
  'Ankara',
  'Berlin',
  'Hanoi',
  'Sydney',
  'Abidjan',
  'Casablanca',
  'Alexandria',
  'Melbourne',
  'Surat',
  'Johannesburg',
  'Dar es Salaam',
  'Shijiazhuang',
  'Harbin',
  'Giza',
  'Zhengzhou',
  'New Taipei City',
  'Birmingham',
  'Toronto',
  'San Francisco',
  'Boston',
  'Washington',
  'Philadelphia',
  'Miami',
  'Atlanta',
  'Houston',
  'Dallas',
  'Phoenix',
  'Denver',
  'Detroit',
  'Minneapolis',
  'Seattle',
  'San Diego',
  'San Jose',
  'Portland',
  'Las Vegas',
  'Salt Lake City',
  'Albuquerque',
  'Kansas City',
  'Omaha',
  'St. Louis',
  'Indianapolis',
  'Columbus',
  'Cleveland',
  'Pittsburgh',
  'Milwaukee',
  'Cincinnati',
  'Nashville',
  'Memphis',
  'Charlotte',
  'Raleigh',
  'Virginia Beach',
  'Jacksonville',
  'Tampa',
  'Orlando',
  'New Orleans',
  'Birmingham',
  'Louisville',
  'Richmond',
  'Baltimore',
  'Buffalo',
  'Providence',
  'Hartford',
  'Albany',
  'Rochester',
  'Syracuse',
];
