# Generated by Django 4.2.2 on 2023-07-05 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Casing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100)),
                ('device_name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('date_start', models.DateField()),
                ('detail', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('item_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('despription', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100)),
                ('phase', models.CharField(choices=[('SMT', 'SMT'), ('THT', 'THT'), ('tunning', 'tunning'), ('monitor assembly', 'monitor assembly'), ('communication config', 'communication config'), ('analysis', 'analysis'), ('correction', 'correction')])),
                ('quantity_in', models.PositiveIntegerField()),
                ('quantity_out', models.PositiveIntegerField()),
                ('date_start', models.DateField()),
                ('detail', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('stock_in', models.PositiveIntegerField()),
                ('stock_out', models.PositiveIntegerField()),
                ('inventory', models.PositiveIntegerField()),
                ('units', models.CharField(max_length=100)),
                ('edit_date', models.DateField()),
                ('edited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.items')),
            ],
        ),
    ]
