# Generated by Django 4.2.2 on 2023-07-06 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_stock_edit_date_alter_stock_edited_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='item_code',
            field=models.ForeignKey(default=104, on_delete=django.db.models.deletion.CASCADE, to='dashboard.items'),
        ),
    ]
