# Generated by Django 4.2.2 on 2023-07-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_stock_item_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casing',
            name='detail',
            field=models.CharField(max_length=1000),
        ),
    ]
