# Generated by Django 4.2.2 on 2023-07-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_casing_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='detail',
            field=models.CharField(max_length=1000),
        ),
    ]
