# Generated by Django 4.2.2 on 2023-07-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_casing_batch_number_alter_casing_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='date_end',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='date_start',
            field=models.DateField(auto_now_add=True),
        ),
    ]
