# Generated by Django 4.2.2 on 2023-08-01 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_remove_stock_inventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='edit_date',
            new_name='stock_out_date',
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_in_date',
            field=models.DateField(default='2023-07-13', null=True),
        ),
    ]
