export const LOAD_HIGHLIGHTS_SUCCESS = 'LOAD_HIGHLIGHTS_SUCCESS';
export const LOAD_HIGHLIGHTS_FAILURE = 'LOAD_HIGHLIGHTS_FAILURE';

export const LOAD_TAGS_SUCCESS = 'LOAD_TAGS_SUCCESS';
export const LOAD_TAGS_FAILURE = 'LOAD_TAGS_FAILURE';