export const LOAD_PM25_HEATMAP_DATA_SUCCESS = "LOAD_PM25_HEATMAP_DATA_SUCCESS";
export const LOAD_PM25_HEATMAP_DATA_FAILURE = "LOAD_PM25_HEATMAP_DATA_FAILURE";

export const LOAD_PM25_SENSOR_DATA_SUCCESS = "LOAD_PM25_SENSOR_DATA_SUCCESS";
export const LOAD_PM25_SENSOR_DATA_FAILURE = "LOAD_PM25_SENSOR_DATA_FAILURE";

export const LOAD_MAP_EVENTS_SUCCESS = "LOAD_MAP_EVENTS_SUCCESS";
export const LOAD_MAP_EVENTS_FAILURE = "LOAD_MAP_EVENTS_FAILURE";

export const LOAD_MAP_SENSORS_DATA_SUCCESS = "LOAD_MAP_SENSORS_DATA_SUCCESS";
export const LOAD_MAP_SENSORS_DATA_FAILURE = "LOAD_MAP_SENSORS_DATA_FAILURE";
