# Generated by Django 4.1.1 on 2022-09-20 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0004_alter_highlight_options_highlight_link_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='highlight',
            options={'ordering': ['order', '-id']},
        ),
    ]
