# Generated by Django 4.2.5 on 2024-02-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0007_alter_highlight_link_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='link_title_en',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='highlight',
            name='link_title_fr',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='highlight',
            name='title_en',
            field=models.CharField(max_length=110, null=True),
        ),
        migrations.AddField(
            model_name='highlight',
            name='title_fr',
            field=models.CharField(max_length=110, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_en',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_fr',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
