# Generated by Django 4.2.5 on 2024-02-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0004_press_article_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='press',
            name='article_intro_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='press',
            name='article_intro_fr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='press',
            name='article_title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='press',
            name='article_title_fr',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
