# Generated by Django 5.0.2 on 2024-02-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_event_event_details_en_event_event_details_fr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_category',
            field=models.CharField(blank=True, choices=[('all', 'All'), ('webinar', 'Webinar'), ('workshop', 'Workshop'), ('marathon', 'Marathon'), ('conference', 'Conference'), ('summit', 'Summit'), ('commemoration', 'Commemoration'), ('others', 'Others')], default='all', max_length=40, null=True),
        ),
    ]
