# Generated by Django 4.1.7 on 2023-11-08 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanair', '0003_cleanairresource_author_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleanairresource',
            name='resource_authors',
            field=models.CharField(default='AirQo', max_length=200),
        ),
    ]
