# Generated by Django 5.0.2 on 2024-04-05 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleanair', '0007_remove_cleanairresource_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleanairresource',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cleanairresource',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='engagement',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='engagement',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='forumevent',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='forumevent',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='person',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='person',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='program',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='program',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='session',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='session',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='support',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='support',
            name='updated_at',
        ),
    ]
