# Generated by Django 5.0.2 on 2024-04-05 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanair', '0010_forumevent_event_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumevent',
            name='event_details',
        ),
        migrations.AlterField(
            model_name='engagement',
            name='forum_event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagement', to='cleanair.forumevent'),
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('details', models.TextField(blank=True, null=True)),
                ('engagement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='cleanair.engagement')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
