# Generated by Django 5.0.2 on 2024-04-05 21:30

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanair', '0011_remove_forumevent_event_details_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objective',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='objective',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_logo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='ForumPartnerImage'),
        ),
        migrations.AlterField(
            model_name='person',
            name='picture',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='PersonImage'),
        ),
    ]
