# Generated by Django 5.0.2 on 2024-04-06 14:55

import cloudinary.models
import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleanair', '0014_alter_forumevent_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumevent',
            name='introduction',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forumevent',
            name='background_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='BackgroundImage'),
        ),
    ]
