# Generated by Django 5.0.2 on 2024-04-06 15:34

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleanair', '0016_alter_forumevent_title_alter_partner_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='biography',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
