# Generated by Django 5.0.2 on 2024-04-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanair', '0019_alter_person_biography'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='website_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
