# Generated by Django 5.0.2 on 2024-04-08 11:50

import backend.cleanair.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanair', '0020_partner_website_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='category',
            field=models.CharField(choices=[('Funding Partner', 'FUNDING_PARTNER'), ('Host Partner', 'HOST_PARTNER'), ('Co-Convening Partner', 'CO_CONVENING_PARTNER')], default=backend.cleanair.models.PartnerCategoryChoices['FUNDING_PARTNER'], max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='category',
            field=models.CharField(choices=[('Speaker', 'SPEAKER'), ('Committee Member', 'COMMITTEE_MEMBER')], default=backend.cleanair.models.CategoryChoices['SPEAKER'], max_length=50),
        ),
    ]
