# Generated by Django 5.0.2 on 2024-04-08 17:35

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleanair', '0021_alter_partner_category_alter_person_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='biography',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
