# Generated by Django 5.0.2 on 2024-04-08 18:28

import django_quill.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanair', '0022_alter_person_biography'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='bio',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
    ]
