# Generated by Django 5.0.2 on 2024-04-09 19:54

import django_quill.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanair', '0024_remove_person_biography'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='section_text',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.TimeField(null=True),
        ),
    ]
