# Generated by Django 5.0.2 on 2024-04-09 20:56

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleanair', '0027_alter_session_session_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_details',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
