# Generated by Django 5.0.2 on 2024-04-11 20:45

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleanair', '0029_alter_forumevent_title_subtext_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_details',
            field=django_quill.fields.QuillField(),
        ),
    ]
