# Generated by Django 5.0.2 on 2024-04-16 22:55

import backend.cleanair.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanair', '0032_alter_session_session_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='category',
            field=models.CharField(choices=[('Speaker', 'SPEAKER'), ('Committee Member', 'COMMITTEE_MEMBER'), ('Key Note Speaker', 'KEY_NOTE_SPEAKER')], default=backend.cleanair.models.CategoryChoices['SPEAKER'], max_length=50),
        ),
    ]
