# Generated by Django 5.0.2 on 2024-04-23 14:11

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleanair', '0033_alter_person_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumevent',
            name='sponsorship_details',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
