# Generated by Django 5.0.2 on 2024-05-01 23:04

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleanair', '0034_forumevent_sponsorship_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='program_details',
            field=django_quill.fields.QuillField(null=True),
        ),
    ]
