# Generated by Django 5.0.2 on 2024-05-01 23:16

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleanair', '0036_alter_program_program_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='program_details',
        ),
        migrations.AddField(
            model_name='program',
            name='sub_text',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
