# Generated by Django 5.0.2 on 2024-05-02 01:01

import backend.cleanair.models
import django_quill.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanair', '0040_rename_sponsorship_opportunities_forumevent_sponsorship_opportunities_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumevent',
            name='partners_text_section',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forumevent',
            name='sponsorship_opportunities_partners',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='category',
            field=models.CharField(choices=[('Funding Partner', 'FUNDING_PARTNER'), ('Host Partner', 'HOST_PARTNER'), ('Co-Convening Partner', 'CO_CONVENING_PARTNER'), ('Programme Partner', 'PROGRAMME_PARTNER')], default=backend.cleanair.models.PartnerCategoryChoices['FUNDING_PARTNER'], max_length=50),
        ),
    ]
