# Generated by Django 5.0.2 on 2024-05-02 01:40

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleanair', '0042_rename_travel_logistics_forumevent_travel_logistics_vaccination_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumevent',
            name='glossary_details',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
