# Generated by Django 5.0.2 on 2024-05-02 13:42

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleanair', '0044_alter_partner_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumevent',
            name='travel_logistics_accommodation_details',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
