# Generated by Django 5.0.2 on 2024-05-31 01:13

import backend.cleanair.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanair', '0046_alter_person_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='category',
            field=models.CharField(choices=[('Speaker', 'SPEAKER'), ('Committee Member', 'COMMITTEE_MEMBER'), ('Key Note Speaker', 'KEY_NOTE_SPEAKER'), ('Speaker and Committee Member', 'SPEAKER_AND_COMMITTEE_MEMBER'), ('Committee Member and Key Note Speaker', 'COMMITTEE_MEMBER_AND_KEY_NOTE_SPEAKER')], default=backend.cleanair.models.CategoryChoices['SPEAKER'], max_length=50),
        ),
    ]
