# Generated by Django 5.0.7 on 2024-08-06 08:52

import django.db.models.deletion
import django_quill.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanair', '0047_alter_person_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_title', models.CharField(max_length=120)),
                ('resource_summary', django_quill.fields.QuillField(blank=True, null=True)),
                ('resource_file', models.FileField(blank=True, null=True, upload_to='cleanair/resources/')),
                ('resource_authors', models.CharField(default='AirQo', max_length=200)),
                ('order', models.IntegerField(default=1)),
                ('forum_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_resources', to='cleanair.forumevent')),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
    ]
