# Generated by Django 5.0.7 on 2024-08-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanair', '0055_alter_resourcesession_forum_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcefile',
            name='resource_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
