# Generated by Django 5.0.7 on 2024-08-12 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanair', '0056_alter_resourcefile_resource_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcefile',
            name='session',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='resource_files', to='cleanair.resourcesession'),
        ),
    ]
