export interface ProjectAnswers {
  directory: string;
  packageName: string;
  orgName: string;
  orgShortName: string;
  orgSlug: string;
  primaryColor: string;
  tileProvider: "openstreetmap" | "mapbox";
  initGit: boolean;
}

/**
 * Renders the scaffolded project's vertex.config.ts. Mirrors the shape of
 * the template's own config file; every key stays editable after
 * scaffolding, and core/config/vertex-config.ts validates it at startup.
 */
export function renderVertexConfig(answers: ProjectAnswers): string {
  const s = (value: string) => JSON.stringify(value);
  return `import {
  defaultVertexConfig,
  validateVertexConfig,
  type VertexConfigInput,
} from "./core/config/vertex-config";

// Generated by create-vertex-app. Every key is editable — see
// vertex.config.example.ts for the annotated reference.
const config: VertexConfigInput = {
  ...defaultVertexConfig,
  org: {
    name: ${s(answers.orgName)},
    shortName: ${s(answers.orgShortName)},
    slug: ${s(answers.orgSlug)},
    logo: "/images/vertex_logo.svg",
    primaryColor: ${s(answers.primaryColor)},
    supportEmail: "support@example.org",
    websiteUrl: "",
  },
  api: {
    // v1 supports "mock" only: the app runs entirely on fixtures,
    // no backend or credentials needed.
    adapter: "mock",
    baseUrl: process.env.NEXT_PUBLIC_API_URL || "",
    publicMeasurementsBaseUrl: process.env.NEXT_PUBLIC_API_BASE_URL || "",
  },
  auth: {
    // v1 supports "none" only: the app boots straight into the
    // dashboard with a synthetic session.
    provider: "none",
    systemGroupSlug: "system",
  },
  features: {
    deviceMap: true,
    bulkDeploy: true,
    siteManagement: true,
    exportCSV: true,
    readingHistory: false,
    userManagement: false,

    appLauncher: false,
    networkRequests: false,
  },
  map: {
    defaultCenter: [0.3476, 32.5825],
    defaultZoom: 11,
    // "openstreetmap" needs no token; "mapbox" requires
    // NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN in the environment.
    tileProvider: ${s(answers.tileProvider)},
  },
  links: {
    docsUrl: "",
    privacyPolicyUrl: "",
    cookiePolicyUrl: "",
    analyticsUrl: "",
  },
};

export const vertexConfig = validateVertexConfig(config);
export default vertexConfig;
`;
}
