# Generated by Django 4.1.1 on 2022-12-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_alter_partner_partner_image_alter_partner_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='type',
            field=models.CharField(blank=True, choices=[('partnership', 'Partnership'), ('collaboration', 'Collaboration'), ('policy', 'Policy'), ('funder', 'Funder'), ('research', 'Research')], default='partnership', max_length=40, null=True),
        ),
    ]
