# Generated by Django 4.1.7 on 2023-09-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_partner_website_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='type',
            field=models.CharField(blank=True, choices=[('partnership', 'Partnership'), ('collaboration', 'Collaboration'), ('policy', 'Policy'), ('funder', 'Funder'), ('research', 'Research'), ('network', 'Network Partner'), ('support', 'Supporting Partner')], default='partnership', max_length=40, null=True),
        ),
    ]
