# Generated by Django 4.2.5 on 2024-02-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0009_alter_partner_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='partner_name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='partner_name_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='partnerdescription',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnerdescription',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
