# Generated by Django 4.1.1 on 2022-09-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0003_auto_20220720_1057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='highlight',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='highlight',
            name='link_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='highlight',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
