export const GET_ERRORS = 'GET_ERRORS';
export const USER_LOADING = 'USER_LOADING';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const GET_USERS_FAILED = 'GET_USERS_FAILED';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';

export const GET_CANDIDATES_FAILED = 'GET_USERS_FAILED';
export const GET_CANDIDATES_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_CANDIDATES_REQUEST = 'GET_USERS_REQUEST';

export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILED = 'REGISTER_USER_FAILED';
export const SHOW_REGISTER_USER = 'SHOW_REGISTER_USER';
export const HIDE_REGISTER_USER = 'HIDE_REGISTER_USER';

export const HIDE_EDIT_DIALOG = 'HIDE_EDIT_DIALOG';
export const SHOW_EDIT_DIALOG = 'SHOW_EDIT_DIALOG';
export const EDIT_USER_REQUEST = 'EDIT_USER_REQUEST';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_FAILED = 'EDIT_USER_FAILED';

export const SHOW_DELETE_DIALOG = 'SHOW_DELETE_DIALOG';
export const HIDE_DELETE_DIALOG = 'HIDE_DELETE_DIALOG';
export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER_FAILED = 'DELETE_USER_FAILED';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';

export const TOGGLE_REGISTER_USER = 'TOGGLE_REGISTER_USER';

export const SHOW_CONFIRM_DIALOG = 'SHOW_CONFIRM_DIALOG';
export const HIDE_CONFIRM_DIALOG = 'HIDE_CONFIRM_DIALOG';
export const CONFIRM_USER_REQUEST = 'CONFIRM_USER_REQUEST';
export const CONFIRM_USER_SUCCESS = 'CONFIRM_USER_SUCCESS';
export const CONFIRM_USER_FAILED = 'CONFIRM_USER_FAILED';

export const SET_DEFAULTS_REQUEST = 'SET_DEFAULTS_REQUEST';
export const SET_DEFAULTS_SUCCESS = 'SET_DEFAULTS_SUCCESS';
export const SET_DEFAULTS_FAILED = 'SET_DEFAULTS_FAILED';

export const UPDATE_PASSWORD_REQUEST = 'UPDATE_PASSWORD_REQUEST';
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS';
export const UPDATE_PASSWORD_FAILED = 'UPDATE_PASSWORD_FAILED';

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PASSWORD_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PASSWORD_SUCCESS';
export const UPDATE_PROFILE_FAILED = 'UPDATE_PASSWORD_FAILED';

export const GET_DEFAULTS_REQUEST = 'UPDATE_PASSWORD_REQUEST';
export const GET_DEFAULTS_SUCCESS = 'UPDATE_PASSWORD_SUCCESS';
export const GET_DEFAULTS_FAILED = 'UPDATE_PASSWORD_FAILED';

export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';

export const UPDATE_AUTHENTICATED_USER_SUCCESS =
    'UPDATE_AUTHENTICATED_USER_SUCCESS';
export const UPDATE_AUTHENTICATED_USER_FAILED =
    'UPDATE_AUTHENTICATED_USER_FAILURE';
export const UPDATE_AUTHENTICATED_USER_REQUEST =
    'UPDATE_AUTHENTICATED_USER_REQUEST';