export type MonitorType = 'LCS' | 'Reference' | 'Inactive';

export type ViewMode = 'monitors' | 'coverage';

export interface MonitorStation {
  id: string;
  name: string;
  city: string;
  country: string;
  iso2: string;
  latitude: number;
  longitude: number;
  type: MonitorType;
  status: 'active' | 'inactive';
  network: string;
  operator: string;
  equipment: string;
  manufacturer: string;
  pollutants: string[];
  resolution: string;
  transmission: string;
  site: string;
  landUse: string;
  deployed: string;
  calibrationLastDate: string;
  calibrationMethod: string;
  uptime30d: string;
  publicData: 'Yes' | 'No';
  organisation: string;
  coLocation: string;
  coLocationNote: string;
  lastActive: string;
}

export interface CountryCoverage {
  id: string;
  country: string;
  iso2: string;
  monitors: MonitorStation[];
}

const AFRICAN_COUNTRY_LIST: Array<{ country: string; iso2: string }> = [
  { country: 'Algeria', iso2: 'DZ' },
  { country: 'Angola', iso2: 'AO' },
  { country: 'Benin', iso2: 'BJ' },
  { country: 'Botswana', iso2: 'BW' },
  { country: 'Burkina Faso', iso2: 'BF' },
  { country: 'Burundi', iso2: 'BI' },
  { country: 'Cabo Verde', iso2: 'CV' },
  { country: 'Cameroon', iso2: 'CM' },
  { country: 'Central African Republic', iso2: 'CF' },
  { country: 'Chad', iso2: 'TD' },
  { country: 'Comoros', iso2: 'KM' },
  { country: 'Congo', iso2: 'CG' },
  { country: 'Democratic Republic of the Congo', iso2: 'CD' },
  { country: "Cote d'Ivoire", iso2: 'CI' },
  { country: 'Djibouti', iso2: 'DJ' },
  { country: 'Egypt', iso2: 'EG' },
  { country: 'Equatorial Guinea', iso2: 'GQ' },
  { country: 'Eritrea', iso2: 'ER' },
  { country: 'Eswatini', iso2: 'SZ' },
  { country: 'Ethiopia', iso2: 'ET' },
  { country: 'Gabon', iso2: 'GA' },
  { country: 'Gambia', iso2: 'GM' },
  { country: 'Ghana', iso2: 'GH' },
  { country: 'Guinea', iso2: 'GN' },
  { country: 'Guinea-Bissau', iso2: 'GW' },
  { country: 'Kenya', iso2: 'KE' },
  { country: 'Lesotho', iso2: 'LS' },
  { country: 'Liberia', iso2: 'LR' },
  { country: 'Libya', iso2: 'LY' },
  { country: 'Madagascar', iso2: 'MG' },
  { country: 'Malawi', iso2: 'MW' },
  { country: 'Mali', iso2: 'ML' },
  { country: 'Mauritania', iso2: 'MR' },
  { country: 'Mauritius', iso2: 'MU' },
  { country: 'Morocco', iso2: 'MA' },
  { country: 'Mozambique', iso2: 'MZ' },
  { country: 'Namibia', iso2: 'NA' },
  { country: 'Niger', iso2: 'NE' },
  { country: 'Nigeria', iso2: 'NG' },
  { country: 'Rwanda', iso2: 'RW' },
  { country: 'Sao Tome and Principe', iso2: 'ST' },
  { country: 'Senegal', iso2: 'SN' },
  { country: 'Seychelles', iso2: 'SC' },
  { country: 'Sierra Leone', iso2: 'SL' },
  { country: 'Somalia', iso2: 'SO' },
  { country: 'South Africa', iso2: 'ZA' },
  { country: 'South Sudan', iso2: 'SS' },
  { country: 'Sudan', iso2: 'SD' },
  { country: 'Tanzania', iso2: 'TZ' },
  { country: 'Togo', iso2: 'TG' },
  { country: 'Tunisia', iso2: 'TN' },
  { country: 'Uganda', iso2: 'UG' },
  { country: 'Zambia', iso2: 'ZM' },
  { country: 'Zimbabwe', iso2: 'ZW' },
];

const monitoredStations: MonitorStation[] = [
  {
    id: 'ug-kcca-ref-01',
    name: 'KCCA Nakawa Reference Station',
    city: 'Kampala',
    country: 'Uganda',
    iso2: 'UG',
    latitude: 0.3314,
    longitude: 32.618,
    type: 'Reference',
    status: 'active',
    network: 'KCCA',
    operator: 'Government',
    equipment: 'GRIMM EDM 180',
    manufacturer: 'GRIMM Aerosol',
    pollutants: ['PM2.5', 'PM10', 'NO2'],
    resolution: 'Hourly',
    transmission: 'GPRS',
    site: 'KCCA offices compound, peri-urban industrial fringe',
    landUse: 'Industrial',
    deployed: 'Jan 2020',
    calibrationLastDate: 'Sept 2025',
    calibrationMethod: 'Factory + annual field check',
    uptime30d: '78%',
    publicData: 'Yes',
    organisation: 'KCCA Environment Department',
    coLocation: 'Available',
    coLocationNote:
      'Formal written application to KCCA Director of Environment required. Allow 4-6 weeks.',
    lastActive: '2h ago',
  },
  {
    id: 'ug-kampala-lcs-01',
    name: 'Kampala CBD LCS Station',
    city: 'Kampala',
    country: 'Uganda',
    iso2: 'UG',
    latitude: 0.315,
    longitude: 32.582,
    type: 'LCS',
    status: 'active',
    network: 'AirQo',
    operator: 'AirQo',
    equipment: 'AirQo v3',
    manufacturer: 'AirQo',
    pollutants: ['PM2.5', 'PM10'],
    resolution: '15 min',
    transmission: '4G',
    site: 'Kampala central business district',
    landUse: 'Urban',
    deployed: 'Jun 2021',
    calibrationLastDate: 'Aug 2025',
    calibrationMethod: 'Quarterly co-location',
    uptime30d: '93%',
    publicData: 'Yes',
    organisation: 'AirQo Research Team',
    coLocation: 'Not available',
    coLocationNote: 'Unit is attached to active power infrastructure.',
    lastActive: '18m ago',
  },
  {
    id: 'ug-naguru-lcs-02',
    name: 'Naguru LCS Node',
    city: 'Kampala',
    country: 'Uganda',
    iso2: 'UG',
    latitude: 0.3431,
    longitude: 32.6143,
    type: 'LCS',
    status: 'active',
    network: 'AirQo',
    operator: 'University',
    equipment: 'AirQo v2',
    manufacturer: 'AirQo',
    pollutants: ['PM2.5', 'PM10'],
    resolution: '15 min',
    transmission: 'WiFi',
    site: 'Naguru neighborhood mast',
    landUse: 'Residential',
    deployed: 'Mar 2022',
    calibrationLastDate: 'Jul 2025',
    calibrationMethod: 'Biannual co-location',
    uptime30d: '88%',
    publicData: 'Yes',
    organisation: 'Makerere University',
    coLocation: 'Available',
    coLocationNote: 'Request is reviewed by the local city lead.',
    lastActive: '1h ago',
  },
  {
    id: 'ug-ntinda-inactive-01',
    name: 'Ntinda Legacy Monitor',
    city: 'Kampala',
    country: 'Uganda',
    iso2: 'UG',
    latitude: 0.3314,
    longitude: 32.618,
    type: 'Inactive',
    status: 'inactive',
    network: 'AirQo',
    operator: 'AirQo',
    equipment: 'AirQo v1',
    manufacturer: 'AirQo',
    pollutants: ['PM2.5'],
    resolution: 'Hourly',
    transmission: '2G',
    site: 'Former Ntinda road post',
    landUse: 'Urban',
    deployed: 'Nov 2019',
    calibrationLastDate: 'May 2024',
    calibrationMethod: 'Manual check',
    uptime30d: '0%',
    publicData: 'No',
    organisation: 'AirQo Ops',
    coLocation: 'Unavailable',
    coLocationNote: 'Node retired from production network.',
    lastActive: '124d ago',
  },
  {
    id: 'ke-nairobi-ref-01',
    name: 'Nairobi Central Reference Station',
    city: 'Nairobi',
    country: 'Kenya',
    iso2: 'KE',
    latitude: -1.2864,
    longitude: 36.8172,
    type: 'Reference',
    status: 'active',
    network: 'NEMA',
    operator: 'Government',
    equipment: 'BAM 1022',
    manufacturer: 'Met One',
    pollutants: ['PM2.5', 'PM10', 'NO2'],
    resolution: 'Hourly',
    transmission: 'Fiber',
    site: 'Nairobi CBD station tower',
    landUse: 'Urban',
    deployed: 'Jan 2021',
    calibrationLastDate: 'Sep 2025',
    calibrationMethod: 'Factory annual + local monthly',
    uptime30d: '94%',
    publicData: 'Yes',
    organisation: 'NEMA Kenya',
    coLocation: 'Available',
    coLocationNote: 'For approved academic collaborations.',
    lastActive: '10m ago',
  },
  {
    id: 'ke-mombasa-lcs-01',
    name: 'Mombasa Port LCS Station',
    city: 'Mombasa',
    country: 'Kenya',
    iso2: 'KE',
    latitude: -4.0435,
    longitude: 39.6682,
    type: 'LCS',
    status: 'active',
    network: 'AirQo',
    operator: 'County',
    equipment: 'AirQo v2',
    manufacturer: 'AirQo',
    pollutants: ['PM2.5', 'PM10'],
    resolution: '15 min',
    transmission: '4G',
    site: 'Near old port customs building',
    landUse: 'Industrial',
    deployed: 'May 2022',
    calibrationLastDate: 'Jul 2025',
    calibrationMethod: 'Quarterly co-location',
    uptime30d: '86%',
    publicData: 'Yes',
    organisation: 'Mombasa County',
    coLocation: 'Available',
    coLocationNote: 'Request through county environment office.',
    lastActive: '1h ago',
  },
  {
    id: 'tz-dar-lcs-01',
    name: 'Dar CBD LCS Station',
    city: 'Dar es Salaam',
    country: 'Tanzania',
    iso2: 'TZ',
    latitude: -6.7924,
    longitude: 39.2083,
    type: 'LCS',
    status: 'active',
    network: 'AirQo',
    operator: 'City Authority',
    equipment: 'AirQo v3',
    manufacturer: 'AirQo',
    pollutants: ['PM2.5', 'PM10'],
    resolution: '15 min',
    transmission: '4G',
    site: 'Central business district rooftop',
    landUse: 'Urban',
    deployed: 'Apr 2023',
    calibrationLastDate: 'Aug 2025',
    calibrationMethod: 'Co-location',
    uptime30d: '91%',
    publicData: 'Yes',
    organisation: 'Dar City Council',
    coLocation: 'Available',
    coLocationNote: 'Approval required from municipal office.',
    lastActive: '21m ago',
  },
  {
    id: 'za-jhb-ref-01',
    name: 'Johannesburg Reference Station',
    city: 'Johannesburg',
    country: 'South Africa',
    iso2: 'ZA',
    latitude: -26.2041,
    longitude: 28.0473,
    type: 'Reference',
    status: 'active',
    network: 'Gauteng AQ',
    operator: 'Government',
    equipment: 'BAM 1020',
    manufacturer: 'Met One',
    pollutants: ['PM2.5', 'PM10', 'NO2'],
    resolution: 'Hourly',
    transmission: 'Fiber',
    site: 'Inner city civic center',
    landUse: 'Urban',
    deployed: 'Feb 2018',
    calibrationLastDate: 'Sep 2025',
    calibrationMethod: 'Factory annual + field',
    uptime30d: '97%',
    publicData: 'Yes',
    organisation: 'Gauteng Province',
    coLocation: 'Available',
    coLocationNote: 'Technical MoU required.',
    lastActive: '8m ago',
  },
  {
    id: 'za-ct-lcs-01',
    name: 'Cape Town LCS Node',
    city: 'Cape Town',
    country: 'South Africa',
    iso2: 'ZA',
    latitude: -33.9249,
    longitude: 18.4241,
    type: 'LCS',
    status: 'active',
    network: 'AirQo',
    operator: 'University',
    equipment: 'AirQo v3',
    manufacturer: 'AirQo',
    pollutants: ['PM2.5', 'PM10'],
    resolution: '15 min',
    transmission: '4G',
    site: 'University campus weather mast',
    landUse: 'Urban',
    deployed: 'May 2024',
    calibrationLastDate: 'Sep 2025',
    calibrationMethod: 'Quarterly co-location',
    uptime30d: '95%',
    publicData: 'Yes',
    organisation: 'UCT Research Hub',
    coLocation: 'Available',
    coLocationNote: 'Subject to safety training.',
    lastActive: '33m ago',
  },
  {
    id: 'ng-lagos-ref-01',
    name: 'Lagos Island Reference Station',
    city: 'Lagos',
    country: 'Nigeria',
    iso2: 'NG',
    latitude: 6.5244,
    longitude: 3.3792,
    type: 'Reference',
    status: 'active',
    network: 'Lagos AQ',
    operator: 'Government',
    equipment: 'TEOM 1405',
    manufacturer: 'Thermo Fisher',
    pollutants: ['PM2.5', 'PM10', 'NO2'],
    resolution: 'Hourly',
    transmission: 'Fiber',
    site: 'Lagos Island civic square',
    landUse: 'Urban',
    deployed: 'Jul 2022',
    calibrationLastDate: 'Sep 2025',
    calibrationMethod: 'Quarterly lab check',
    uptime30d: '92%',
    publicData: 'Yes',
    organisation: 'LASEPA',
    coLocation: 'Available',
    coLocationNote: 'Partnership request required.',
    lastActive: '14m ago',
  },
  {
    id: 'ng-abuja-lcs-01',
    name: 'Abuja LCS Node',
    city: 'Abuja',
    country: 'Nigeria',
    iso2: 'NG',
    latitude: 9.0765,
    longitude: 7.3986,
    type: 'LCS',
    status: 'active',
    network: 'AirQo',
    operator: 'AirQo',
    equipment: 'AirQo v3',
    manufacturer: 'AirQo',
    pollutants: ['PM2.5', 'PM10'],
    resolution: '15 min',
    transmission: '4G',
    site: 'Federal capital district rooftop',
    landUse: 'Urban',
    deployed: 'Nov 2023',
    calibrationLastDate: 'Aug 2025',
    calibrationMethod: 'Co-location',
    uptime30d: '89%',
    publicData: 'Yes',
    organisation: 'AirQo Nigeria',
    coLocation: 'Not available',
    coLocationNote: 'Reserved for federal observation program.',
    lastActive: '44m ago',
  },
  {
    id: 'gh-accra-lcs-01',
    name: 'Accra Ring Road LCS Station',
    city: 'Accra',
    country: 'Ghana',
    iso2: 'GH',
    latitude: 5.6037,
    longitude: -0.187,
    type: 'LCS',
    status: 'active',
    network: 'AirQo',
    operator: 'University',
    equipment: 'AirQo v3',
    manufacturer: 'AirQo',
    pollutants: ['PM2.5', 'PM10'],
    resolution: '15 min',
    transmission: '4G',
    site: 'Near Ring Road central corridor',
    landUse: 'Urban',
    deployed: 'Oct 2024',
    calibrationLastDate: 'Aug 2025',
    calibrationMethod: 'Co-location',
    uptime30d: '90%',
    publicData: 'Yes',
    organisation: 'University of Ghana',
    coLocation: 'Available',
    coLocationNote: 'Partner institutions prioritized.',
    lastActive: '29m ago',
  },
  {
    id: 'eg-cairo-ref-01',
    name: 'Cairo Reference Node',
    city: 'Cairo',
    country: 'Egypt',
    iso2: 'EG',
    latitude: 30.0444,
    longitude: 31.2357,
    type: 'Reference',
    status: 'active',
    network: 'Cairo AQ',
    operator: 'Government',
    equipment: 'AQM 65',
    manufacturer: 'Aeroqual',
    pollutants: ['PM2.5', 'PM10', 'NO2'],
    resolution: 'Hourly',
    transmission: 'Fiber',
    site: 'Downtown Cairo municipality tower',
    landUse: 'Urban',
    deployed: 'Dec 2020',
    calibrationLastDate: 'Sep 2025',
    calibrationMethod: 'Annual lab calibration',
    uptime30d: '96%',
    publicData: 'Yes',
    organisation: 'Egyptian Environmental Affairs Agency',
    coLocation: 'Not available',
    coLocationNote: 'Public agency restricted access site.',
    lastActive: '11m ago',
  },
];

const slugify = (value: string) =>
  value
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .trim();

export const networkCoverageMockData: CountryCoverage[] =
  AFRICAN_COUNTRY_LIST.map(({ country, iso2 }) => ({
    id: slugify(country),
    country,
    iso2,
    monitors: monitoredStations.filter((station) => station.iso2 === iso2),
  }));

export const africanIso2Codes = AFRICAN_COUNTRY_LIST.map((item) => item.iso2);
