name: app
description: AirQo mobile application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# android test
version: 2.1.3+20058

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  shared_preferences: ^2.2.0
  google_maps_flutter: ^2.3.1
  json_annotation: ^4.8.1
  http: ^0.13.6
  cached_network_image: ^3.2.3
  geolocator: ^10.1.0
  flutter_local_notifications: ^17.2.2
  path_provider: ^2.0.15
  animations: ^2.0.7
  provider: ^6.0.5
  intl: any
  uuid: ^3.0.7
  flutter_svg: ^2.0.7
  image_picker: ^1.0.1
  country_list_pick: ^1.0.1+6
  shimmer: ^3.0.0
  google_fonts: ^4.0.4
  in_app_review: ^2.0.6
  lottie: ^2.5.0
  share_plus: ^7.0.2
  flutter_secure_storage: ^9.0.0
  flutter_dotenv: ^5.1.0
  auto_size_text: ^3.0.0
  firebase_core: ^2.15.0
  firebase_messaging: ^14.6.5
  cloud_firestore: ^4.8.3
  firebase_auth: ^4.7.1
  firebase_analytics: ^10.4.4
  firebase_storage: ^11.2.5
  package_info_plus: ^4.0.2
  webview_flutter: ^4.2.2
  hive: ^2.2.3
  retry: ^3.0.0
  hive_flutter: ^1.1.0
  firebase_in_app_messaging: ^0.7.3+4
  permission_handler: ^11.0.1
  workmanager: ^0.5.1
  flutter_cache_manager: ^3.3.1
  path: ^1.8.3
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  appinio_swiper: 2.0.2
  firebase_dynamic_links: ^5.3.4
  showcaseview: ^3.0.0
  url_launcher: ^6.1.12
  hydrated_bloc: ^9.1.2
  home_widget: ^0.6.0
  geocoding: ^2.1.0
  rating_dialog: ^2.0.4
  confetti: ^0.7.0
  animated_text_kit: ^4.2.2
  connectivity_plus: ^5.0.1

  # Drift previous database => airqo_app_db.sqlite

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
  flutter_lints: ^3.0.1
  build_runner: ^2.3.3
  json_serializable: ^6.6.0
  dart_code_metrics: ^5.5.0
  hive_generator: ^2.0.0
  bloc_test: ^9.1.1
  restart_app: ^1.2.1
  flutter_native_splash: ^2.3.9

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icon/
    - assets/lottie/
    - .env.dev
    - .env.prod
    - shorebird.yaml

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400        
        
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500

        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600 

        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700 

        - asset: assets/fonts/Inter-Black.ttf
          weight: 800 

flutter_native_splash:
  # Background color of splash screen
  color: "#ffffff"
  # Image that you want to show
  image: assets/images/airQo-logo.png
  # Sizing of image
  # Splash Image to show in dark mode (Optional)
  # image_dark: assets/images/airQo-logo.png
  # Background color of dark mode (Optional)
  # color_dark: "#000000"
  android_12:
    # The image parameter sets the splash screen icon image.  If this parameter is not specified,
    # the app's launcher icon will be used instead.
    # Please note that the splash screen will be clipped to a circle on the center of the screen.
    # App icon with an icon background: This should be 960×960 pixels, and fit within a circle
    # 640 pixels in diameter.
    # App icon without an icon background: This should be 1152×1152 pixels, and fit within a circle
    # 768 pixels in diameter.
    image: assets/images/airQo-logo2.png

    # Splash screen background color.
    color: "#ffffff"

    # App icon background color.
    #icon_background_color: "#111111"

    # The branding property allows you to specify an image used as branding in the splash screen.
    #branding: assets/dart.png

    # The image_dark, color_dark, icon_background_color_dark, and branding_dark set values that
    # apply when the device is in dark mode. If they are not specified, the app will use the
    # parameters from above.
    # image_dark: assets/images/airQo-logo.png

    color_dark: "#ffffff"
    #icon_background_color_dark: "#eeeeee"

