version: '3'

tasks:

  run:
    desc: Runs the app in dev mode
    aliases: ['r']
    dotenv: ['.env.dev']
    preconditions:
      - flutter gen-l10n
    cmds:
      - flutter run --flavor=airqo

  tests:
    desc: Runs tests with coverage
    aliases: ['t']
    cmds:
      - flutter test --coverage

  coverage-report:
    desc: Generates and opens test coverage report
    cmds:
      - genhtml coverage/lcov.info -o coverage/html
      - open coverage/html/index.html

  code-format:
    desc: Code formatting
    cmds:
      - dart fix --dry-run
      - dart fix --apply
      - dart format lib/
      - dart format test/

  build-runner:
    desc: Build runner
    cmds:
      - dart run build_runner build --delete-conflicting-outputs

  configure-firebase:
    desc: Configures firebase
    cmds:
      - flutterfire configure
      - mv ios/Runner/GoogleService-Info.plist ios/config/airqo/GoogleService-Info.plist
      - mv android/app/google-services.json android/app/src/airqo/google-services.json

  build-android:
    desc: Builds android for release
    aliases: ['ba']
    dotenv: ['.env.prod']
    preconditions:
      - flutter clean
    cmds:
      - flutter build appbundle --build-name=$VERSION --build-number=$BUILD_NUMBER --flavor=airqo --obfuscate --split-debug-info=${PWD}/obfuscate

  build-ios:
    desc: Builds ios for release
    aliases: ['bi']
    platforms: [darwin]
    dotenv: ['.env.prod']
    preconditions:
      - sed -i '' "s/GOOGLE_API_KEY/$IOS_GOOGLE_API_KEY/g" ios/Runner/AppDelegate.swift
      - flutter clean
    cmds:
      - flutter build ipa --build-name=$VERSION --build-number=$BUILD_NUMBER --flavor=airqo --obfuscate --split-debug-info=${PWD}/obfuscate
      - defer: { task: ios-build-cleanup }

  ios-build-cleanup:
    desc: Performs cleaning after building iOS
    dotenv: ['.env.prod']
    cmds:
      - sed -i '' "s/$IOS_GOOGLE_API_KEY/GOOGLE_API_KEY/g" ios/Runner/AppDelegate.swift

  upgrade-dependencies:
    aliases: ['ud']
    desc: Upgrades dependencies
    preconditions:
      - flutter clean
      - rm -rf ios/Pods
      - rm -rf ios/.symlinks
      - rm ios/Podfile.lock
      - rm pubspec.lock
    cmds:
      - flutter pub add firebase_core shared_preferences google_maps_flutter json_annotation http
      - flutter pub add geolocator flutter_local_notifications path_provider animations provider
      - flutter pub add intl country_list_pick uuid flutter_svg image_picker
      - flutter pub add shimmer google_fonts in_app_review lottie
      - flutter pub add share_plus flutter_secure_storage geocoding flutter_dotenv auto_size_text
      - flutter pub add cached_network_image firebase_messaging cloud_firestore firebase_auth firebase_analytics
      - flutter pub add firebase_storage package_info_plus webview_flutter hive hive_flutter
      - flutter pub add firebase_in_app_messaging permission_handler workmanager flutter_cache_manager
      - flutter pub add path flutter_bloc equatable appinio_swiper firebase_dynamic_links
      - flutter pub add showcaseview url_launcher hydrated_bloc
      - cd ios || exit 1
      - pod repo update
      - pod install
