replicaCount: 2
image:
  repository: eu.gcr.io/airqo-250220/airqo-vertex
  tag: prod-f298409d-1755687932
  pullPolicy: Always
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
service:
  type: NodePort
  nodePort: 30113
  targetPort: 3000
  port: 3000
ingress:
  enabled: false
nodeSelector:
  role: high-mem
tolerations: {}
resources:
  requests:
    cpu: 10m
    memory: 20Mi
  limits:
    cpu: 50m
    memory: 150Mi
autoscaling:
  minReplicas: 1
  maxReplicas: 2
  targetMemoryUtilizationPercentage: 70
affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - preference:
          matchExpressions:
            - key: role
              operator: In
              values:
                - control-plane
        weight: 1
app:
  name: airqo-vertex
  label: vertex
  namespace: production
  configmap: env-vertex-production
