# Generated by Django 4.2.5 on 2024-02-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('africancities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='africancountry',
            name='country_name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='africancountry',
            name='country_name_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='city_name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='city_name_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='title_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='title_fr',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='description',
            name='paragraph_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='description',
            name='paragraph_fr',
            field=models.TextField(null=True),
        ),
    ]
