// contains all the action creator functions.
export const LOAD_ALL_LOCATIONS_SUCCESS = "LOAD_ALL_LOCATIONS_SUCCESS";
export const LOAD_ALL_LOCATIONS_FAILURE = "LOAD_ALL_LOCATIONS_FAILURE";
export const RESET_LOCATIONS_SUCCESS = "RESET_LOCATIONS_SUCCESS";
