name: google_mlkit_translation
description: Temporary local stub used to unblock iOS simulator builds.
version: 0.13.0
publish_to: 'none'

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  meta: ^1.9.1
