# Generated by Django 4.0.5 on 2022-06-13 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_alter_member_linked_in_alter_member_twitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='linked_in',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='twitter',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
