# Generated by Django 4.0.5 on 2022-06-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_alter_member_linked_in_alter_member_twitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
