# Generated by Django 3.2.14 on 2022-07-18 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_alter_member_options_member_is_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['order', 'name']},
        ),
    ]
