# Generated by Django 4.2.2 on 2023-07-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_phone_number_profile_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='staff',
            new_name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='permission_level',
            field=models.CharField(choices=[('view', 'view'), ('edit', 'edit'), ('admin', 'admin')], default=0, max_length=10),
            preserve_default=False,
        ),
    ]
