export const LOAD_TEAM_SUCCESS = 'LOAD_TEAM_SUCCESS';
export const LOAD_TEAM_FAILURE = 'LOAD_TEAM_FAILURE';

export const UPDATE_TEAM_LOADER_SUCCESS = 'UPDATE_TEAM_LOADER_SUCCESS';
export const UPDATE_TEAM_LOADER_FAILURE = 'UPDATE_TEAM_LOADER_FAILURE';