/** @type {import('ts-jest').JestConfigWithTsJest} */
module.exports = {
  preset: 'ts-jest/presets/js-with-ts-esm',
  testEnvironment: 'jsdom',
  setupFilesAfterEnv: ['<rootDir>/src/__mocks__/setup.ts'],
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
    '^@/components/(.*)$': '<rootDir>/src/components/$1',
    '^@/features/(.*)$': '<rootDir>/src/features/$1',
    '\\.(css|scss|sass)$': 'identity-obj-proxy',
    '\\.(jpg|jpeg|png|gif|webp|avif|ico|bmp|svg)$':
      '<rootDir>/src/__mocks__/fileMock.ts',
    '^mapbox-gl$': '<rootDir>/src/__mocks__/mapbox-gl.ts',
    '^recharts$': '<rootDir>/src/__mocks__/recharts.tsx',
  },
  testMatch: [
    '<rootDir>/src/**/__tests__/**/*.{ts,tsx}',
    '<rootDir>/src/**/*.{spec,test}.{ts,tsx}',
  ],
  coverageProvider: 'v8',
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'lcov', 'clover'],
  collectCoverageFrom: [
    'src/**/*.{ts,tsx}',
    '!src/**/*.d.ts',
    '!src/**/*.stories.{ts,tsx}',
    '!src/__mocks__/**',
    '!src/types/**',
    '!src/app/**',
    '!src/features/**',
    '!src/components/**',
    '!src/styles/**',
    '!src/lib/metadata/**',
    '!src/lib/analytics/**',
    '!src/lib/devcon.ts',
    '!src/lib/navItems.ts',
    '!src/lib/metadata.ts',
    '!src/services/external/**',
    '!src/services/website/**',
    '!src/hooks/endpointsNew.ts',
    '!src/hooks/index.ts',
    '!src/hooks/useApiHooks.tsx',
    '!src/queries/index.ts',
    '!src/queries/query-client.ts',
    '!src/services/api/index.ts',
    '!src/services/api/api-error.ts',
    '!src/services/api/api-response.ts',
    '!src/store/index.ts',
    '!src/config/env.config.ts',
    '!src/config/images.config.ts',
    '!src/config/seo.config.ts',
    '!src/config/site.config.ts',
    '!src/lib/utils/googleTranslate.ts',
    '!src/lib/utils/index.ts',
  ],
  transform: {
    '^.+\\.(ts|tsx)$': [
      'ts-jest',
      {
        tsconfig: 'tsconfig.json',
        jsx: 'react-jsx',
      },
    ],
  },
  testPathIgnorePatterns: [
    '<rootDir>/node_modules/',
    '<rootDir>/.next/',
    '<rootDir>/e2e/',
    '<rootDir>/coverage/',
  ],
  modulePathIgnorePatterns: ['<rootDir>/.next/standalone/'],
};
