// contains all the action creator functions.
export const LOAD_SITES_SUCCESS = 'LOAD_SITES_SUCCESS';
export const LOAD_SITES_FAILURE = 'LOAD_SITES_FAILURE';

export const LOAD_SITE_OPTIONS_SUCCESS = 'LOAD_SITE_OPTIONS_SUCCESS';
export const LOAD_SITE_OPTIONS_FAILURE = 'LOAD_SITE_OPTIONS_FAILURE';

export const LOAD_SITES_SUMMARY_SUCCESS = 'LOAD_SITES_SUMMARY_SUCCESS';
export const LOAD_SITES_SUMMARY_FAILURE = 'LOAD_SITES_SUMMARY_FAILURE';

export const GET_SITE_DETAILS_SUCCESS = 'GET_SITE_DETAILS_SUCCESS';
export const GET_SITE_DETAILS_FAILURE = 'GET_SITE_DETAILS_FAILURE';
