// Re-export all hooks from the new implementation
export {
  useAfricanCountries,
  useAfricanCountryDetail,
  useAirQoEvents,
  useBoardMembers,
  useCareerDetail,
  useCareers,
  useCleanAirEvents,
  useCleanAirResources,
  useCohortMeasurements,
  useCohortsSummary,
  useCountriesData,
  useDailyForecast,
  useDepartments,
  useEventDetails,
  useExternalTeamBiography,
  useExternalTeamMembers,
  useFAQs,
  useForumEventDetails,
  useForumEvents,
  useForumEventTitles,
  useGridMeasurements,
  useGridRepresentativeReading,
  useGridsSummary,
  useGridsSummaryExternal,
  useGridsSummaryV2,
  useHighlights,
  useImpactNumbers,
  usePartnerDetails,
  usePartners,
  usePastEvents,
  usePressArticles,
  usePublications,
  useTeamBiography,
  useTeamMembers,
  useUpcomingEvents,
} from '@/services/hooks/endpointsNew';
