export const UPDATE_DEVICE_OVERVIEW_BACK_URL_SUCCESS =
  "UPDATE_DEVICE_OVERVIEW_BACK_URL_SUCCESS";
export const UPDATE_DEVICE_OVERVIEW_BACK_URL_FAILURE =
  "UPDATE_DEVICE_OVERVIEW_BACK_URL_FAILURE";
