import type { Config } from 'jest';

const config: Config = {
  testEnvironment: 'jsdom',
  roots: ['<rootDir>/src'],
  testMatch: ['**/__tests__/**/*.test.{ts,tsx}', '**/*.test.{ts,tsx}'],
  transform: {
    '^.+\\.tsx?$': [
      'ts-jest',
      {
        tsconfig: 'tsconfig.json',
        jsx: 'react-jsx',
      },
    ],
  },
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
    '\\.(css|less|scss|sass)$': 'identity-obj-proxy',
    '\\.(jpg|jpeg|png|gif|svg)$': '<rootDir>/src/__mocks__/fileMock.ts',
    '^mapbox-gl$': '<rootDir>/src/__mocks__/mapbox-gl.ts',
    '^recharts$': '<rootDir>/src/__mocks__/recharts.tsx',
  },
  setupFilesAfterEnv: ['<rootDir>/src/__mocks__/setup.ts'],
  coverageProvider: 'v8',
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'json-summary'],
  collectCoverageFrom: [
    'src/**/*.{ts,tsx}',
    '!src/**/*.d.ts',
    '!src/**/index.ts',
    '!src/app/**',
    '!src/__mocks__/**',
    '!src/**/__tests__/**',
    '!src/shared/components/**',
    '!src/modules/*/components/**',
    '!src/shared/providers/**',
    '!src/shared/layouts/**',
    '!src/shared/hooks/useAdmin.ts',
    '!src/shared/hooks/useAnalytics.ts',
    '!src/shared/hooks/useAuth.ts',
    '!src/shared/hooks/useChecklist.ts',
    '!src/shared/hooks/useClient.ts',
    '!src/shared/hooks/useDevice.ts',
    '!src/shared/hooks/useDevicesData.ts',
    '!src/shared/hooks/useGroups.ts',
    '!src/shared/hooks/useLogout.ts',
    '!src/shared/hooks/usePageTracking.ts',
    '!src/shared/hooks/usePreferences.ts',
    '!src/shared/hooks/useRBAC.ts',
    '!src/shared/hooks/useResizeObserver.ts',
    '!src/shared/hooks/useSitesData.ts',
    '!src/shared/hooks/useSubscription.ts',
    '!src/shared/hooks/useUser.ts',
    '!src/shared/hooks/useUserActions.ts',
    '!src/shared/hooks/redux.ts',
    '!src/shared/hooks/useEnvironmentAwareUrl.ts',
    '!src/shared/services/adminService.ts',
    '!src/shared/services/analyticsService.ts',
    '!src/shared/services/applicationEmailConfigService.ts',
    '!src/shared/services/checklistService.ts',
    '!src/shared/services/clientService.ts',
    '!src/shared/services/deviceService.ts',
    '!src/shared/services/learnAdminService.ts',
    '!src/shared/services/maintenanceService.ts',
    '!src/shared/services/preferencesService.ts',
    '!src/shared/services/sessionAuthToken.ts',
    '!src/shared/services/subscriptionService.ts',
    '!src/shared/services/surveyService.ts',
    '!src/shared/services/userService.ts',
    '!src/shared/lib/auth.ts',
    '!src/shared/lib/auth-redirect.ts',
    '!src/shared/lib/clientCache.ts',
    '!src/shared/lib/image.ts',
    '!src/shared/lib/logger.ts',
    '!src/shared/lib/metadata.ts',
    '!src/shared/lib/paddle.ts',
    '!src/shared/lib/utils.ts',
    '!src/shared/lib/validators.ts',
    '!src/shared/lib/validation-limits.ts',
    '!src/shared/utils/cloudinaryUpload.ts',
    '!src/shared/utils/dateUtils.ts',
    '!src/shared/utils/enhancedAnalytics.ts',
    '!src/shared/utils/analytics.ts',
    '!src/shared/utils/analyticsConstants.ts',
    '!src/shared/utils/refreshWithToast.ts',
    '!src/shared/utils/url.ts',
    '!src/shared/types/**',
    '!src/modules/airqo-map/hooks/**',
    '!src/modules/airqo-map/services/**',
    '!src/modules/analytics/hooks/**',
    '!src/modules/data-download/hooks/**',
    '!src/modules/data-download/utils/**',
    '!src/modules/data-visualizer/**',
    '!src/modules/feedback/services/**',
    '!src/modules/themes/hooks/**',
    '!src/modules/themes/services/**',
    '!src/modules/themes/providers/**',
    '!src/modules/organization/**',
    '!src/modules/location-insights/**',
    '!src/modules/user-profile/**',
    '!src/modules/user-checklist/index.tsx',
    '!src/modules/*/*.tsx',
    '!src/modules/**/types/**',
    '!src/shared/services/apiClient.ts',
    '!src/modules/api-client/**',
    '!src/modules/billing/**',
    '!src/modules/data-download/DataExportPage.tsx',
    '!src/modules/user-checklist/Checklist.tsx',
    '!src/modules/feedback/**/*.tsx',
    '!src/modules/themes/**/*.tsx',
    '!src/modules/analytics/**/*.tsx',
  ],
  coveragePathIgnorePatterns: [
    '/node_modules/',
    '/__mocks__/',
    '/__tests__/',
    '\\.d\\.ts$',
  ],
  testPathIgnorePatterns: ['/node_modules/', '/.next/', '/e2e/', '/coverage/'],
};

export default config;
