/************ maintenance records ************************************** */
export const GET_MAINTENANCE_FAILED = "GET_MAINTENANCE_FAILED";
export const GET_MAINTENANCE_SUCCESS = "GET_MAINTENANCE_SUCCESS";
export const GET_MAINTENANCE_REQUEST = "GET_MAINTENANCE_REQUEST";

export const EDIT_MAITENANCE_REQUEST = "EDIT_MAINTENANCE_REQUEST";
export const EDIT_MAINTENANCE_SUCCESS = "EDIT_MAINTENANCE_SUCCESS";
export const EDIT_MAINTENANCE_FAILED = "EDIT_MAINTENANCE_FAILED";

export const DELETE_MAINTENANCE_REQUEST = "DELETE_MAINTENANCE_REQUEST";
export const DELETE_MAINTENANCE_FAILED = "DELETE_MAINTENANCE_FAILED";
export const DELETE_MAINTENANCE_SUCCESS = "DELETE_MAINTENANCE_SUCCESS";

/************ device issues *********************************************/
export const GET_ISSUES_FAILED = "GET_ISSUES_FAILED";
export const GET_ISSUES_SUCCESS = "GET_ISSUES_SUCCESS";
export const GET_ISSUES_REQUEST = "GET_ISSUES_REQUEST";

export const EDIT_ISSUE_REQUEST = "EDIT_ISSUE_REQUEST";
export const EDIT_ISSUE_SUCCESS = "EDIT_ISSUE_SUCCESS";
export const EDIT_ISSUE_FAILED = "EDIT_ISSUE_FAILED";

export const DELETE_ISSUE_REQUEST = "DELETE_ISSUE_REQUEST";
export const DELETE_ISSUE_FAILED = "DELETE_ISSUE_FAILED";
export const DELETE_ISSUE_SUCCESS = "DELETE_ISSUE_SUCCESS";

/*************** Dialog Boxes ********************************************/
export const HIDE_EDIT_DIALOG = "HIDE_EDIT_DIALOG";
export const SHOW_EDIT_DIALOG = "SHOW_EDIT_DIALOG";
export const SHOW_DELETE_DIALOG = "SHOW_DELETE_DIALOG";
export const HIDE_DELETE_DIALOG = "HIDE_DELETE_DIALOG";
