export const EXPLORE_DATA_REQUEST_SUCCESS = 'EXPLORE_DATA_REQUEST_SUCCESS';

export const EXPLORE_DATA_REQUEST_FAILURE = 'EXPLORE_DATA_REQUEST_FAILURE';

export const SET_USER_ORGANISATION_SUCCESS = 'SET_USER_ORGANISATION_SUCCESS';

export const SET_USER_ORGANISATION_FAILURE = 'SET_USER_ORGANISATION_FAILURE';

export const SET_USER_CATEGORY_SUCCESS = 'SET_USER_CATEGORY_SUCCESS';

export const SET_USER_CATEGORY_FAILURE = 'SET_USER_CATEGORY_FAILURE';