export const UPDATE_EXPLORE_DATA_SUCCESS = 'UPDATE_EXPLORE_DATA_SUCCESS';
export const UPDATE_EXPLORE_DATA_FAILURE = 'UPDATE_EXPLORE_DATA_FAILURE ';

export const EXPLORE_DATA_REQUEST_SUCCESS = 'EXPLORE_DATA_REQUEST_SUCCESS';
export const EXPLORE_DATA_REQUEST_FAILURE = 'EXPLORE_DATA_REQUEST_FAILURE';

export const SHOW_EXPLORE_DATA_MODAL_SUCCESS = 'SHOW_EXPLORE_DATA_MODAL_SUCCESS';
export const SHOW_EXPLORE_DATA_MODAL_FAILURE = 'SHOW_EXPLORE_DATA_MODAL_FAILURE';