# Generated by Django 4.2.2 on 2023-07-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_production_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casing',
            name='batch_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='casing',
            name='detail',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='casing',
            name='device_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='casing',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='detail',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='phase',
            field=models.CharField(choices=[('SMT', 'SMT'), ('THT', 'THT'), ('tunning', 'tunning'), ('monitor assembly', 'monitor assembly'), ('communication config', 'communication config'), ('analysis', 'analysis'), ('correction', 'correction')], null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='quantity_in',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='quantity_out',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='inventory',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='item_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_in',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_out',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='units',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
