# Generated by Django 4.2.2 on 2023-07-17 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_production_date_end_alter_production_date_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='edited_by',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='item_code',
        ),
        migrations.DeleteModel(
            name='Items',
        ),
    ]
