# Generated by Django 4.2.2 on 2023-07-17 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_stock_edited_by_remove_stock_item_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='inventory',
        ),
    ]
