# Generated by Django 4.2.2 on 2023-08-08 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_historicalstock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalStock',
        ),
    ]
