# Generated by Django 4.2.2 on 2023-08-15 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_delete_historicalstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(null=True)),
                ('stock_in', models.PositiveIntegerField(null=True)),
                ('stock_out', models.PositiveIntegerField(null=True)),
                ('stock_in_date', models.DateField(null=True)),
                ('stock_out_date', models.DateField(null=True)),
                ('history_date', models.DateTimeField(auto_now_add=True)),
                ('Stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.stock')),
            ],
        ),
    ]
