# Generated by Django 4.2.2 on 2023-08-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_stockhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistory',
            name='history_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
