# Generated by Django 4.2.2 on 2023-08-16 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_stockhistory_history_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockhistory',
            name='Stock',
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='history_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.stock'),
        ),
    ]
