export const CREATE_POLYGON = "CREATE_POLYGON";
export const EDIT_POLYGON = "CREATE_POLYGON";
export const RENDER_MAP_DEFAULTS = "RENDER_MAP_DEFAULTS";
export const RESET_MAP_DEFAULTS_SUCCESS = "RESET_MAP_DEFAULTS_SUCCESS";
