default_platform(:android)

platform :android do

  desc "Deploy a new version to alpha track"
  lane :alpha do
    #TODO: Review when plugin is updated
    # previous_build_number = google_play_track_version_codes(
    #   package_name: CredentialsManager::AppfileConfig.try_fetch_value(:package_name),
    #   track: "alpha",
    #   json_key: CredentialsManager::AppfileConfig.try_fetch_value(:json_key_file),
    # )[0].to_i 

    # current_build_number = (previous_build_number) + 1

    # increment_version_code(
    #   gradle_file_path: "app/build.gradle",
    #   version_code: current_build_number.to_i,
    # )

    gradle(task: "bundleAirqoRelease")
    upload_to_play_store(
      version_name: "2.0.12",
      version_code: "20024",
      release_status: "draft",
      metadata_path:"metadata",
      track: "alpha",
      json_key: CredentialsManager::AppfileConfig.try_fetch_value(:json_key_file),
      package_name: CredentialsManager::AppfileConfig.try_fetch_value(:package_name),
      aab: "/Users/mutabazinble/GitHub/AirQo-frontend/mobile/build/app/outputs/bundle/airqoRelease/app-airqo-release.aab",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      validate_only: true,
      skip_upload_apk: true,
    )
  end

  desc "Deploy to new version to Firebase App Distribution"
  lane :distribute do
    firebase_app_distribution(
      app: ENV['MOBILE_ANDROID_ID_FIREBASE'],
      android_artifact_path:"/home/runner/work/AirQo-frontend/AirQo-frontend/mobile/build/app/outputs/bundle/airqoRelease/app-airqo-release.aab",
      release_notes_file: "/home/runner/work/AirQo-frontend/AirQo-frontend/mobile/android/release_notes.txt",
      service_credentials_file: "/home/runner/work/AirQo-frontend/AirQo-frontend/mobile/android/firebase_distributor.json",
      android_artifact_type: "AAB",
      testers_file: "/home/runner/work/AirQo-frontend/AirQo-frontend/mobile/android/testers.txt"
      )
  end
end
