default_platform(:android)

platform :android do

  desc "Deploy a new version to alpha track"
  lane :production do
  
    gradle(task: "bundleAirqoRelease")
    upload_to_play_store(
      version_name: "2.0.13",
      version_code: "20025",
      release_status: "draft",
      metadata_path:"metadata",
      json_key: CredentialsManager::AppfileConfig.try_fetch_value(:json_key_file),
      package_name: CredentialsManager::AppfileConfig.try_fetch_value(:package_name),
      aab: "../build/app/outputs/bundle/airqoRelease/app-airqo-release.aab",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      validate_only: true,
      skip_upload_apk: true,
    )
  end

  desc "Deploy to new version to Firebase App Distribution"
  lane :distribute do
    gradle(task: "bundleAirqoRelease")
    firebase_app_distribution(
      app: ENV['MOBILE_ANDROID_ID_FIREBASE'],
      android_artifact_path:"../build/app/outputs/bundle/airqoRelease/app-airqo-release.aab",
      release_notes_file: "fastlane/release_notes.txt",
      service_credentials_file: "fastlane/firebase-app-distribution.json",
      android_artifact_type: "AAB",
      groups: "airqo-team",
      )
  end
end
