export const LOAD_BOARD_SUCCESS = 'LOAD_BOARD_SUCCESS';
export const LOAD_BOARD_FAILURE = 'LOAD_BOARD_FAILURE';

export const UPDATE_BOARD_LOADER_SUCCESS = 'UPDATE_BOARD_LOADER_SUCCESS';
export const UPDATE_BOARD_LOADER_FAILURE = 'UPDATE_BOARD_LOADER_FAILURE';
