# Generated by Django 4.1.7 on 2023-09-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0002_alter_press_date_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='press',
            name='website_category',
            field=models.CharField(blank=True, choices=[('airqo', 'AirQo'), ('cleanair', 'CleanAir')], default='airqo', max_length=40, null=True),
        ),
    ]
