version: '3.9'

services:
  # Production-oriented service (default)
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - '3000:3000'
    restart: unless-stopped
    networks:
      - app-net

  # Development service: use with `--profile dev`
  app-dev:
    profiles: [dev]
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - ./:/app:cached
      # Keep node_modules inside the container to avoid host/OS mismatches
      - /app/node_modules
    ports:
      - '3000:3000'
    command: yarn dev
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
