// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnndi5DpiTdNiTPoOBHdG7L4XBHBde_lk',
    appId: '1:702081712633:android:f5cff1cf6238701b993d28',
    messagingSenderId: '702081712633',
    projectId: 'airqo-250220',
    databaseURL: 'https://airqo-250220.firebaseio.com',
    storageBucket: 'airqo-250220.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB07U6kGkhTgUh8J-or_mYoRir2oTVvj7c',
    appId: '1:702081712633:ios:8ff0fdc991729ee0993d28',
    messagingSenderId: '702081712633',
    projectId: 'airqo-250220',
    databaseURL: 'https://airqo-250220.firebaseio.com',
    storageBucket: 'airqo-250220.appspot.com',
    androidClientId:
        '702081712633-2m55tnj0njsgt4hnekmavgpf8js67a3r.apps.googleusercontent.com',
    iosClientId:
        '702081712633-3tgp25ii9bktfrtjbcm1ubn5s43dmu9t.apps.googleusercontent.com',
    iosBundleId: 'com.airqo.net',
  );

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }
}
