// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcra-90bskaBWH8i-B_TR9EDeYQO36r_I',
    appId: '1:394593516776:android:89d626c5cd0c10fa9e1d5d',
    messagingSenderId: '394593516776',
    projectId: 'airqo-dev',
    databaseURL:
        'https://console.firebase.google.com/u/1/project/airqo-dev/database',
    storageBucket: 'airqo-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcra-90bskaBWH8i-B_TR9EDeYQO36r_I',
    appId: '1:394593516776:ios:68b713e52cbf0feb9e1d5d',
    messagingSenderId: '394593516776',
    projectId: 'airqo-dev',
    databaseURL: 'https://airqo-250220.firebaseio.com',
    storageBucket: 'airqo-dev.appspot.com',
    androidClientId:
        '702081712633-2m55tnj0njsgt4hnekmavgpf8js67a3r.apps.googleusercontent.com',
    iosClientId:
        '702081712633-3tgp25ii9bktfrtjbcm1ubn5s43dmu9t.apps.googleusercontent.com',
    iosBundleId: 'com.airqo.net',
  );
}
