export interface Language {
  code: string;
  name: string;
  flag: string; // ISO country code for flag (e.g., 'us', 'gb', 'fr')
  country: string;
  region: string;
}

// Helper function to get flag URL from country code
export const getFlagUrl = (countryCode: string): string => {
  return `https://flagcdn.com/w80/${countryCode.toLowerCase()}.png`;
};

// Curated list of languages based on AirQo's target regions
export const languages: Language[] = [
  // Default
  {
    code: 'en',
    name: 'English (US)',
    flag: 'us',
    country: 'United States',
    region: 'Global',
  },
  {
    code: 'en-GB',
    name: 'English (UK)',
    flag: 'gb',
    country: 'United Kingdom',
    region: 'Europe',
  },

  // Africa - Comprehensive list of Google Translate supported languages
  {
    code: 'af',
    name: 'Afrikaans',
    flag: 'za',
    country: 'South Africa',
    region: 'Africa',
  },
  {
    code: 'aa',
    name: 'Afar',
    flag: 'dj',
    country: 'Djibouti/Eritrea/Ethiopia',
    region: 'Africa',
  },
  {
    code: 'am',
    name: 'Amharic',
    flag: 'et',
    country: 'Ethiopia',
    region: 'Africa',
  },
  {
    code: 'ar',
    name: 'Arabic',
    flag: 'eg',
    country: 'North Africa',
    region: 'Africa',
  },
  {
    code: 'bm',
    name: 'Bambara',
    flag: 'ml',
    country: 'Mali',
    region: 'Africa',
  },
  {
    code: 'ny',
    name: 'Chichewa',
    flag: 'mw',
    country: 'Malawi',
    region: 'Africa',
  },
  {
    code: 'ee',
    name: 'Ewe',
    flag: 'gh',
    country: 'Ghana/Togo',
    region: 'Africa',
  },
  {
    code: 'fon',
    name: 'Fon',
    flag: 'bj',
    country: 'Benin',
    region: 'Africa',
  },
  {
    code: 'gaa',
    name: 'Ga',
    flag: 'gh',
    country: 'Ghana',
    region: 'Africa',
  },
  {
    code: 'ha',
    name: 'Hausa',
    flag: 'ng',
    country: 'Nigeria',
    region: 'Africa',
  },
  {
    code: 'ig',
    name: 'Igbo',
    flag: 'ng',
    country: 'Nigeria',
    region: 'Africa',
  },
  {
    code: 'kg',
    name: 'Kikongo',
    flag: 'cd',
    country: 'Democratic Republic of Congo',
    region: 'Africa',
  },
  {
    code: 'ki',
    name: 'Kikuyu',
    flag: 'ke',
    country: 'Kenya',
    region: 'Africa',
  },
  {
    code: 'rw',
    name: 'Kinyarwanda',
    flag: 'rw',
    country: 'Rwanda',
    region: 'Africa',
  },
  {
    code: 'kri',
    name: 'Krio',
    flag: 'sl',
    country: 'Sierra Leone',
    region: 'Africa',
  },
  {
    code: 'ln',
    name: 'Lingala',
    flag: 'cd',
    country: 'Democratic Republic of Congo',
    region: 'Africa',
  },
  {
    code: 'lg',
    name: 'Luganda',
    flag: 'ug',
    country: 'Uganda',
    region: 'Africa',
  },
  {
    code: 'luo',
    name: 'Luo',
    flag: 'ke',
    country: 'Kenya',
    region: 'Africa',
  },
  {
    code: 'mg',
    name: 'Malagasy',
    flag: 'mg',
    country: 'Madagascar',
    region: 'Africa',
  },
  {
    code: 'nqo',
    name: 'NKo',
    flag: 'gn',
    country: 'Guinea',
    region: 'Africa',
  },
  {
    code: 'om',
    name: 'Oromo',
    flag: 'et',
    country: 'Ethiopia',
    region: 'Africa',
  },
  {
    code: 'pcm',
    name: 'Nigerian Pidgin',
    flag: 'ng',
    country: 'Nigeria',
    region: 'Africa',
  },
  {
    code: 'rn',
    name: 'Rundi',
    flag: 'bi',
    country: 'Burundi',
    region: 'Africa',
  },
  {
    code: 'nso',
    name: 'Sepedi',
    flag: 'za',
    country: 'South Africa',
    region: 'Africa',
  },
  {
    code: 'sn',
    name: 'Shona',
    flag: 'zw',
    country: 'Zimbabwe',
    region: 'Africa',
  },
  {
    code: 'so',
    name: 'Somali',
    flag: 'so',
    country: 'Somalia',
    region: 'Africa',
  },
  {
    code: 'sw',
    name: 'Swahili',
    flag: 'ke',
    country: 'East Africa',
    region: 'Africa',
  },
  {
    code: 'ss',
    name: 'Swati',
    flag: 'sz',
    country: 'Eswatini/South Africa',
    region: 'Africa',
  },
  {
    code: 'tzm',
    name: 'Tamazight',
    flag: 'ma',
    country: 'Morocco',
    region: 'Africa',
  },
  {
    code: 'ti',
    name: 'Tigrinya',
    flag: 'er',
    country: 'Eritrea/Ethiopia',
    region: 'Africa',
  },
  {
    code: 'ts',
    name: 'Tsonga',
    flag: 'za',
    country: 'South Africa/Mozambique',
    region: 'Africa',
  },
  {
    code: 'tw',
    name: 'Twi',
    flag: 'gh',
    country: 'Ghana',
    region: 'Africa',
  },
  {
    code: 've',
    name: 'Venda',
    flag: 'za',
    country: 'South Africa',
    region: 'Africa',
  },
  {
    code: 'wo',
    name: 'Wolof',
    flag: 'sn',
    country: 'Senegal',
    region: 'Africa',
  },
  {
    code: 'xh',
    name: 'Xhosa',
    flag: 'za',
    country: 'South Africa',
    region: 'Africa',
  },
  {
    code: 'yo',
    name: 'Yoruba',
    flag: 'ng',
    country: 'Nigeria',
    region: 'Africa',
  },
  {
    code: 'zu',
    name: 'Zulu',
    flag: 'za',
    country: 'South Africa',
    region: 'Africa',
  },

  // Europe
  {
    code: 'es',
    name: 'Spanish',
    flag: 'es',
    country: 'Spain/S.America',
    region: 'Europe',
  },
  {
    code: 'de',
    name: 'German',
    flag: 'de',
    country: 'Germany',
    region: 'Europe',
  },
  {
    code: 'it',
    name: 'Italian',
    flag: 'it',
    country: 'Italy',
    region: 'Europe',
  },
  {
    code: 'pl',
    name: 'Polish',
    flag: 'pl',
    country: 'Poland',
    region: 'Europe',
  },
  {
    code: 'nl',
    name: 'Dutch',
    flag: 'nl',
    country: 'Netherlands',
    region: 'Europe',
  },
  {
    code: 'ru',
    name: 'Russian',
    flag: 'ru',
    country: 'Russia',
    region: 'Europe',
  },
  {
    code: 'sv',
    name: 'Swedish',
    flag: 'se',
    country: 'Sweden',
    region: 'Europe',
  },
  {
    code: 'fi',
    name: 'Finnish',
    flag: 'fi',
    country: 'Finland',
    region: 'Europe',
  },

  // Asia
  {
    code: 'zh-CN',
    name: 'Chinese (Simplified)',
    flag: 'cn',
    country: 'China',
    region: 'Asia',
  },
  { code: 'hi', name: 'Hindi', flag: 'in', country: 'India', region: 'Asia' },
  {
    code: 'ja',
    name: 'Japanese',
    flag: 'jp',
    country: 'Japan',
    region: 'Asia',
  },
  {
    code: 'ko',
    name: 'Korean',
    flag: 'kr',
    country: 'South Korea',
    region: 'Asia',
  },
  { code: 'th', name: 'Thai', flag: 'th', country: 'Thailand', region: 'Asia' },
  {
    code: 'vi',
    name: 'Vietnamese',
    flag: 'vn',
    country: 'Vietnam',
    region: 'Asia',
  },
  {
    code: 'id',
    name: 'Indonesian',
    flag: 'id',
    country: 'Indonesia',
    region: 'Asia',
  },
];
