// contains all the action creator functions.
export const LOAD_ACTIVITY_SUCCESS = 'LOAD_ACTIVITY_SUCCESS';
export const LOAD_ACTIVITY_FAILURE = 'LOAD_ACTIVITY_FAILURE';

export const LOAD_ACTIVITY_OPTIONS_SUCCESS = 'LOAD_ACTIVITY_OPTIONS_SUCCESS';
export const LOAD_ACTIVITY_OPTIONS_FAILURE = 'LOAD_ACTIVITY_OPTIONS_FAILURE';

export const LOAD_ACTIVITIES_SUMMARY_SUCCESS = 'LOAD_ACTIVITIES_SUMMARY_SUCCESS';
export const LOAD_ACTIVITIES_SUMMARY_FAILURE = 'LOAD_ACTIVITYS_SUMMARY_FAILURE';

export const GET_ACTIVITY_DETAILS_SUCCESS = 'GET_ACTIVITY_DETAILS_SUCCESS';
export const GET_ACTIVITY_DETAILS_FAILURE = 'GET_ACTIVITY_DETAILS_FAILURE';
