name: safe-checks

permissions:
  contents: read

on:
  pull_request:
    branches:
      - staging

jobs:

  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      website: ${{ steps.check.outputs.website }}
      vertex: ${{ steps.check.outputs.vertex }}
      platform: ${{ steps.check.outputs.platform }}
      beacon: ${{ steps.check.outputs.beacon }}
      calibrate: ${{ steps.check.outputs.calibrate }}
      docs: ${{ steps.check.outputs.docs }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: detect changed services
        id: check
        run: |
          git diff --name-only "origin/${{ github.base_ref }}"...HEAD > files.txt
          cat files.txt

          echo "website=false"   >> $GITHUB_OUTPUT
          echo "vertex=false"    >> $GITHUB_OUTPUT
          echo "platform=false"  >> $GITHUB_OUTPUT
          echo "beacon=false"    >> $GITHUB_OUTPUT
          echo "calibrate=false" >> $GITHUB_OUTPUT
          echo "docs=false"      >> $GITHUB_OUTPUT

          while IFS= read -r file
          do
            if [[ $file == src/website/* ]]; then
              echo "website=true" >> $GITHUB_OUTPUT
            fi
            if [[ $file == src/vertex/* ]]; then
              echo "vertex=true" >> $GITHUB_OUTPUT
            fi
            if [[ $file == src/platform/* ]]; then
              echo "platform=true" >> $GITHUB_OUTPUT
            fi
            if [[ $file == src/beacon/* ]]; then
              echo "beacon=true" >> $GITHUB_OUTPUT
            fi
            if [[ $file == src/calibrate/* ]]; then
              echo "calibrate=true" >> $GITHUB_OUTPUT
            fi
            if [[ $file == src/docs-website/* ]]; then
              echo "docs=true" >> $GITHUB_OUTPUT
            fi
          done < files.txt
  check-website:
    needs: detect-changes
    if: needs.detect-changes.outputs.website == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: src/website/package-lock.json
      - name: Install dependencies
        run: cd src/website && npm ci
      - name: Lint
        run: cd src/website && npm run lint --if-present

  check-vertex:
    needs: detect-changes
    if: needs.detect-changes.outputs.vertex == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: src/vertex/package-lock.json
      - name: Install dependencies
        run: cd src/vertex && npm ci
      - name: Lint
        run: cd src/vertex && npm run lint --if-present

  check-platform:
      needs: detect-changes
      if: needs.detect-changes.outputs.platform == 'true'
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
          with:
            persist-credentials: false
        - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af
          with:
            node-version: '20'
            cache: 'yarn'
            cache-dependency-path: src/platform/yarn.lock
        - name: Install dependencies
          run: cd src/platform && yarn install --frozen-lockfile
        - name: Lint
          run: cd src/platform && yarn lint --if-present

  check-beacon:
    needs: detect-changes
    if: needs.detect-changes.outputs.beacon == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: src/beacon/package-lock.json
      - name: Install dependencies
        run: cd src/beacon && npm ci
      - name: Lint
        run: cd src/beacon && npm run lint --if-present
      - name: Build
        run: cd src/beacon && npm run build --if-present

  check-calibrate:
    needs: detect-changes
    if: needs.detect-changes.outputs.calibrate == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: src/calibrate/package-lock.json
      - name: Install dependencies
        run: cd src/calibrate && npm ci
      - name: Lint
        run: cd src/calibrate && npm run lint --if-present
      - name: Build
        run: cd src/calibrate && npm run build --if-present

  check-docs:
    needs: detect-changes
    if: needs.detect-changes.outputs.docs == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: src/docs-website/package-lock.json
      - name: Install dependencies
        run: cd src/docs-website && npm ci
      - name: Lint
        run: cd src/docs-website && npm run lint --if-present
      - name: Build
        run: cd src/docs-website && npm run build --if-present