# Generated by Django 5.0.2 on 2024-04-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanair', '0009_forumevent_author_forumevent_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumevent',
            name='event_tag',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('featured', 'Featured')], default='none', max_length=40, null=True),
        ),
    ]
