# Generated by Django 5.0.2 on 2024-04-05 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanair', '0012_alter_objective_options_objective_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='forum_event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagements', to='cleanair.forumevent'),
        ),
    ]
