# Generated by Django 5.0.2 on 2024-04-11 20:18

import django_quill.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanair', '0028_alter_session_session_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumevent',
            name='title_subtext',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_details',
            field=django_quill.fields.QuillField(null=True),
        ),
    ]
