# Generated by Django 5.0.2 on 2024-04-14 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleanair', '0030_alter_session_session_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumevent',
            name='event_tag',
        ),
    ]
