# Generated by Django 5.0.2 on 2024-04-16 22:46

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleanair', '0031_remove_forumevent_event_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_details',
            field=django_quill.fields.QuillField(null=True),
        ),
    ]
