# Generated by Django 5.0.2 on 2024-05-01 23:28

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleanair', '0037_remove_program_program_details_program_sub_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumevent',
            name='schedule_details',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
