# Generated by Django 5.0.2 on 2024-05-01 23:58

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleanair', '0038_forumevent_schedule_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forumevent',
            old_name='sponsorship_details',
            new_name='sponsorship_opportunities',
        ),
        migrations.AddField(
            model_name='forumevent',
            name='sponsorship_packages',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
