# Generated by Django 5.0.2 on 2024-05-02 13:34

import backend.cleanair.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanair', '0043_forumevent_glossary_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='category',
            field=models.CharField(choices=[('Funding Partner', 'FUNDING_PARTNER'), ('Host Partner', 'HOST_PARTNER'), ('Co-Convening Partner', 'CO_CONVENING_PARTNER'), ('Sponsor Partner', 'SPONSOR_PARTNER')], default=backend.cleanair.models.PartnerCategoryChoices['FUNDING_PARTNER'], max_length=50),
        ),
    ]
