# Generated by Django 4.1.7 on 2023-03-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
