# Generated by Django 4.1.7 on 2023-03-23 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_session_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['order']},
        ),
    ]
