# Generated by Django 4.1.7 on 2023-04-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='resource',
            field=models.FileField(blank=True, null=True, upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
