# Generated by Django 4.1.7 on 2023-09-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_resource_resource_alter_resource_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='website_category',
            field=models.CharField(blank=True, choices=[('airqo', 'AirQo'), ('cleanair', 'CleanAir')], default='airqo', max_length=40, null=True),
        ),
    ]
