# Generated by Django 4.2.5 on 2024-02-06 15:19

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_event_website_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_details_en',
            field=django_quill.fields.QuillField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_details_fr',
            field=django_quill.fields.QuillField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_tag_en',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('featured', 'Featured')], default='none', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_tag_fr',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('featured', 'Featured')], default='none', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location_link_en',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location_link_fr',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location_name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location_name_fr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='title_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='title_subtext_en',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='title_subtext_fr',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='website_category_en',
            field=models.CharField(blank=True, choices=[('airqo', 'AirQo'), ('cleanair', 'CleanAir')], default='airqo', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='website_category_fr',
            field=models.CharField(blank=True, choices=[('airqo', 'AirQo'), ('cleanair', 'CleanAir')], default='airqo', max_length=40, null=True),
        ),
    ]
