# Generated by Django 4.2.5 on 2024-02-06 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_event_event_details_en_event_event_details_fr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='website_category_en',
        ),
        migrations.RemoveField(
            model_name='event',
            name='website_category_fr',
        ),
    ]
