# Generated by Django 4.2.5 on 2024-02-06 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_remove_event_website_category_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_tag_en',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_tag_fr',
        ),
    ]
