# Generated by Django 4.2.5 on 2024-02-06 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_remove_event_event_tag_en_remove_event_event_tag_fr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location_link_en',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location_link_fr',
        ),
    ]
