# Generated by Django 5.0.2 on 2024-02-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_alter_event_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_category',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('webinar', 'Webinar'), ('workshop', 'Workshop'), ('marathon', 'Marathon'), ('conference', 'Conference'), ('summit', 'Summit'), ('commemoration', 'Commemoration')], default='none', max_length=40, null=True),
        ),
    ]
