# Generated by Django 4.2.5 on 2024-02-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_remove_event_location_link_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='inquiry_en',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='inquiry_fr',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='role_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='role_fr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
