# Generated by Django 4.2.5 on 2024-02-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_inquiry_inquiry_en_inquiry_inquiry_fr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='program_details_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='program_details_fr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
