# Generated by Django 4.2.5 on 2024-02-06 15:39

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_program_program_details_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_details_en',
            field=django_quill.fields.QuillField(null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='session_details_fr',
            field=django_quill.fields.QuillField(null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='session_title_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='session_title_fr',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
