# Generated by Django 4.2.5 on 2024-02-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_session_session_details_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='link_en',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='link_fr',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='title_fr',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
