# Generated by Django 4.2.5 on 2024-02-06 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_resource_link_en_resource_link_fr_resource_title_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='link_en',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='link_fr',
        ),
    ]
