# Generated by Django 4.2.5 on 2024-02-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_remove_resource_link_en_remove_resource_link_fr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='role_en',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='role_fr',
        ),
        migrations.AddField(
            model_name='partnerlogo',
            name='name_en',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='partnerlogo',
            name='name_fr',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='venue_en',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='venue_fr',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
