# Generated by Django 4.2.5 on 2024-02-06 17:42

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0017_remove_inquiry_inquiry_en_remove_inquiry_inquiry_fr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='inquiry_en',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='inquiry_fr',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='partnerlogo',
            name='name_en',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='partnerlogo',
            name='name_fr',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='program_details_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='program_details_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='session_details_en',
            field=django_quill.fields.QuillField(null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='session_details_fr',
            field=django_quill.fields.QuillField(null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='session_title_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='session_title_fr',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='venue_en',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='venue_fr',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
