# Generated by Django 4.2.5 on 2024-02-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0018_inquiry_inquiry_en_inquiry_inquiry_fr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_link_en',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_link_fr',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='unique_title_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='unique_title_fr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='role_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='role_fr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='link_en',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='link_fr',
            field=models.URLField(blank=True, null=True),
        ),
    ]
