# Generated by Django 4.2.5 on 2024-02-06 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0019_event_registration_link_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='registration_link_en',
        ),
        migrations.RemoveField(
            model_name='event',
            name='registration_link_fr',
        ),
        migrations.RemoveField(
            model_name='event',
            name='unique_title_en',
        ),
        migrations.RemoveField(
            model_name='event',
            name='unique_title_fr',
        ),
    ]
