# Generated by Django 4.2.5 on 2024-02-06 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0020_remove_event_registration_link_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='link_en',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='link_fr',
        ),
    ]
